/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImDrawListFlags implements NativeEnum<ImDrawListFlags> {

    CUSTOM(0),
    None(ImDrawListFlags_None_NATIVE()),
    AntiAliasedLines(ImDrawListFlags_AntiAliasedLines_NATIVE()),
    AntiAliasedLinesUseTex(ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE()),
    AntiAliasedFill(ImDrawListFlags_AntiAliasedFill_NATIVE()),
    AllowVtxOffset(ImDrawListFlags_AllowVtxOffset_NATIVE()),
    TextNoPixelSnap(ImDrawListFlags_TextNoPixelSnap_NATIVE());

    private int value;

    private ImDrawListFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImDrawListFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImDrawListFlags getCustom() {
        return CUSTOM;
    }

    private static int ImDrawListFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImDrawListFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImDrawListFlags_AntiAliasedLines_NATIVE() {
        try {
            return (int) FFMHandles.ImDrawListFlags_AntiAliasedLines_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE() {
        try {
            return (int) FFMHandles.ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImDrawListFlags_AntiAliasedFill_NATIVE() {
        try {
            return (int) FFMHandles.ImDrawListFlags_AntiAliasedFill_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImDrawListFlags_AllowVtxOffset_NATIVE() {
        try {
            return (int) FFMHandles.ImDrawListFlags_AllowVtxOffset_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImDrawListFlags_TextNoPixelSnap_NATIVE() {
        try {
            return (int) FFMHandles.ImDrawListFlags_TextNoPixelSnap_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImDrawListFlags_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imdrawlistflags_imdrawlistflags_none_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImDrawListFlags_AntiAliasedLines_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imdrawlistflags_imdrawlistflags_antialiasedlines_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imdrawlistflags_imdrawlistflags_antialiasedlinesusetex_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImDrawListFlags_AntiAliasedFill_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imdrawlistflags_imdrawlistflags_antialiasedfill_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImDrawListFlags_AllowVtxOffset_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imdrawlistflags_imdrawlistflags_allowvtxoffset_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImDrawListFlags_TextNoPixelSnap_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imdrawlistflags_imdrawlistflags_textnopixelsnap_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
