/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum ImGuiListClipperFlags implements NativeEnum<ImGuiListClipperFlags> {

    CUSTOM(0), None(ImGuiListClipperFlags_None_NATIVE()), NoSetTableRowCounters(ImGuiListClipperFlags_NoSetTableRowCounters_NATIVE());

    private int value;

    private ImGuiListClipperFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImGuiListClipperFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImGuiListClipperFlags getCustom() {
        return CUSTOM;
    }

    private static int ImGuiListClipperFlags_None_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiListClipperFlags_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int ImGuiListClipperFlags_NoSetTableRowCounters_NATIVE() {
        try {
            return (int) FFMHandles.ImGuiListClipperFlags_NoSetTableRowCounters_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle ImGuiListClipperFlags_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguilistclipperflags_imguilistclipperflags_none_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle ImGuiListClipperFlags_NoSetTableRowCounters_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_enums_imguilistclipperflags_imguilistclipperflags_nosettablerowcounters_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
