/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ImDrawListFlags implements NativeEnum<ImDrawListFlags> {

    CUSTOM(0),
    None(ImDrawListFlags_None_NATIVE()),
    AntiAliasedLines(ImDrawListFlags_AntiAliasedLines_NATIVE()),
    AntiAliasedLinesUseTex(ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE()),
    AntiAliasedFill(ImDrawListFlags_AntiAliasedFill_NATIVE()),
    AllowVtxOffset(ImDrawListFlags_AllowVtxOffset_NATIVE()),
    TextNoPixelSnap(ImDrawListFlags_TextNoPixelSnap_NATIVE());

    private int value;

    private ImDrawListFlags(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ImDrawListFlags setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ImDrawListFlags getCustom() {
        return CUSTOM;
    }

    private static int ImDrawListFlags_None_NATIVE() {
        return imgui.enums.natives.JNI_ImDrawListFlags.ImDrawListFlags_None_NATIVE();
    }

    private static int ImDrawListFlags_AntiAliasedLines_NATIVE() {
        return imgui.enums.natives.JNI_ImDrawListFlags.ImDrawListFlags_AntiAliasedLines_NATIVE();
    }

    private static int ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE() {
        return imgui.enums.natives.JNI_ImDrawListFlags.ImDrawListFlags_AntiAliasedLinesUseTex_NATIVE();
    }

    private static int ImDrawListFlags_AntiAliasedFill_NATIVE() {
        return imgui.enums.natives.JNI_ImDrawListFlags.ImDrawListFlags_AntiAliasedFill_NATIVE();
    }

    private static int ImDrawListFlags_AllowVtxOffset_NATIVE() {
        return imgui.enums.natives.JNI_ImDrawListFlags.ImDrawListFlags_AllowVtxOffset_NATIVE();
    }

    private static int ImDrawListFlags_TextNoPixelSnap_NATIVE() {
        return imgui.enums.natives.JNI_ImDrawListFlags.ImDrawListFlags_TextNoPixelSnap_NATIVE();
    }
}
