/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImFontAtlas extends NativeObject {

    private ImFont ImFont_TEMP_GEN_0;

    private ImFont ImFont_TEMP_GEN_1;

    private ImFont ImFont_TEMP_GEN_2;

    private ImFont ImFont_TEMP_GEN_3;

    private ImFont ImFont_TEMP_GEN_4;

    private ImFont ImFont_TEMP_GEN_5;

    private ImFont ImFont_TEMP_GEN_6;

    private ImFont ImFont_TEMP_GEN_7;

    private ImFont ImFont_TEMP_GEN_8;

    static public final ImFontAtlas NULL = ImFontAtlas.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImFontAtlas(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImFontAtlas native_new() {
        return new ImFontAtlas((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImFontAtlas.internal_native_deleteNative(this_addr);
    }

    public ImFont AddFont(ImFontConfig font_cfg) {
        long addr = internal_native_AddFont_addr(native_address, font_cfg.native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_0 == null)
            ImFont_TEMP_GEN_0 = ImFont.native_new();
        ImFont_TEMP_GEN_0.internal_reset(addr, false);
        return ImFont_TEMP_GEN_0;
    }

    public static long internal_native_AddFont_addr(long this_addr, long font_cfg_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFont_addr(this_addr, font_cfg_addr);
    }

    public ImFont AddFontDefault(ImFontConfig font_cfg) {
        long addr = internal_native_AddFontDefault_addr(native_address, font_cfg.native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_1 == null)
            ImFont_TEMP_GEN_1 = ImFont.native_new();
        ImFont_TEMP_GEN_1.internal_reset(addr, false);
        return ImFont_TEMP_GEN_1;
    }

    public static long internal_native_AddFontDefault_addr(long this_addr, long font_cfg_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontDefault_addr(this_addr, font_cfg_addr);
    }

    public ImFont AddFontDefault() {
        long addr = internal_native_AddFontDefault_addr(native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_2 == null)
            ImFont_TEMP_GEN_2 = ImFont.native_new();
        ImFont_TEMP_GEN_2.internal_reset(addr, false);
        return ImFont_TEMP_GEN_2;
    }

    public static long internal_native_AddFontDefault_addr(long this_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontDefault_addr(this_addr);
    }

    public ImFont AddFontDefaultVector(ImFontConfig font_cfg) {
        long addr = internal_native_AddFontDefaultVector_addr(native_address, font_cfg.native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_3 == null)
            ImFont_TEMP_GEN_3 = ImFont.native_new();
        ImFont_TEMP_GEN_3.internal_reset(addr, false);
        return ImFont_TEMP_GEN_3;
    }

    public static long internal_native_AddFontDefaultVector_addr(long this_addr, long font_cfg_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontDefaultVector_addr(this_addr, font_cfg_addr);
    }

    public ImFont AddFontDefaultVector() {
        long addr = internal_native_AddFontDefaultVector_addr(native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_4 == null)
            ImFont_TEMP_GEN_4 = ImFont.native_new();
        ImFont_TEMP_GEN_4.internal_reset(addr, false);
        return ImFont_TEMP_GEN_4;
    }

    public static long internal_native_AddFontDefaultVector_addr(long this_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontDefaultVector_addr(this_addr);
    }

    public ImFont AddFontDefaultBitmap(ImFontConfig font_cfg) {
        long addr = internal_native_AddFontDefaultBitmap_addr(native_address, font_cfg.native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_5 == null)
            ImFont_TEMP_GEN_5 = ImFont.native_new();
        ImFont_TEMP_GEN_5.internal_reset(addr, false);
        return ImFont_TEMP_GEN_5;
    }

    public static long internal_native_AddFontDefaultBitmap_addr(long this_addr, long font_cfg_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontDefaultBitmap_addr(this_addr, font_cfg_addr);
    }

    public ImFont AddFontDefaultBitmap() {
        long addr = internal_native_AddFontDefaultBitmap_addr(native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_6 == null)
            ImFont_TEMP_GEN_6 = ImFont.native_new();
        ImFont_TEMP_GEN_6.internal_reset(addr, false);
        return ImFont_TEMP_GEN_6;
    }

    public static long internal_native_AddFontDefaultBitmap_addr(long this_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontDefaultBitmap_addr(this_addr);
    }

    public ImFont AddFontFromMemoryTTF(NativeObject font_data, int font_data_size, int size_pixels, ImFontConfig font_cfg) {
        long addr = internal_native_AddFontFromMemoryTTF_addr(native_address, font_data.native_void_address, font_data_size, size_pixels, font_cfg.native_address);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_7 == null)
            ImFont_TEMP_GEN_7 = ImFont.native_new();
        ImFont_TEMP_GEN_7.internal_reset(addr, false);
        return ImFont_TEMP_GEN_7;
    }

    public static long internal_native_AddFontFromMemoryTTF_addr(long this_addr, long font_data_addr, int font_data_size, int size_pixels, long font_cfg_addr) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontFromMemoryTTF_addr(this_addr, font_data_addr, font_data_size, size_pixels, font_cfg_addr);
    }

    public ImFont AddFontFromMemoryTTF(NativeObject font_data, int font_data_size, int size_pixels) {
        long addr = internal_native_AddFontFromMemoryTTF_addr(native_address, font_data.native_void_address, font_data_size, size_pixels);
        if (addr == 0)
            return ImFont.NULL;
        if (ImFont_TEMP_GEN_8 == null)
            ImFont_TEMP_GEN_8 = ImFont.native_new();
        ImFont_TEMP_GEN_8.internal_reset(addr, false);
        return ImFont_TEMP_GEN_8;
    }

    public static long internal_native_AddFontFromMemoryTTF_addr(long this_addr, long font_data_addr, int font_data_size, int size_pixels) {
        return imgui.natives.JNI_ImFontAtlas.internal_native_AddFontFromMemoryTTF_addr(this_addr, font_data_addr, font_data_size, size_pixels);
    }

    public void ClearFonts() {
        internal_native_ClearFonts(native_address);
    }

    public static void internal_native_ClearFonts(long this_addr) {
        imgui.natives.JNI_ImFontAtlas.internal_native_ClearFonts(this_addr);
    }
}
