/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiSizeCallbackData extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    private ImVec2 ImVec2_TEMP_GEN_2;

    static public final ImGuiSizeCallbackData NULL = ImGuiSizeCallbackData.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiSizeCallbackData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSizeCallbackData native_new() {
        return new ImGuiSizeCallbackData((byte) 0, (char) 0);
    }

    public NativeObject get_UserData() {
        long addr = internal_native_get_UserData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_UserData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiSizeCallbackData.internal_native_get_UserData_addr(this_addr);
    }

    public ImVec2 get_Pos() {
        long addr = internal_native_get_Pos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_get_Pos_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiSizeCallbackData.internal_native_get_Pos_addr(this_addr);
    }

    public ImVec2 get_CurrentSize() {
        long addr = internal_native_get_CurrentSize_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_1;
    }

    public static long internal_native_get_CurrentSize_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiSizeCallbackData.internal_native_get_CurrentSize_addr(this_addr);
    }

    public ImVec2 get_DesiredSize() {
        long addr = internal_native_get_DesiredSize_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_2 == null)
            ImVec2_TEMP_GEN_2 = ImVec2.native_new();
        ImVec2_TEMP_GEN_2.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_2;
    }

    public static long internal_native_get_DesiredSize_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiSizeCallbackData.internal_native_get_DesiredSize_addr(this_addr);
    }

    public void set_DesiredSize(ImVec2 DesiredSize) {
        internal_native_set_DesiredSize(native_address, DesiredSize.native_address);
    }

    public static void internal_native_set_DesiredSize(long this_addr, long DesiredSize_addr) {
        imgui.natives.JNI_ImGuiSizeCallbackData.internal_native_set_DesiredSize(this_addr, DesiredSize_addr);
    }
}
