/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import imgui.enums.ImGuiViewportFlags;

public final class ImGuiViewport extends NativeObject {

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    private NativeString NativeString_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_2;

    private ImVec2 ImVec2_TEMP_GEN_3;

    private ImVec2 ImVec2_TEMP_GEN_4;

    private ImVec2 ImVec2_TEMP_GEN_5;

    private ImVec2 ImVec2_TEMP_GEN_6;

    private ImGuiViewport ImGuiViewport_TEMP_GEN_0;

    private ImDrawData ImDrawData_TEMP_GEN_0;

    private NativeObject NativeObject_TEMP_GEN_0;

    private NativeObject NativeObject_TEMP_GEN_1;

    private NativeObject NativeObject_TEMP_GEN_2;

    private NativeObject NativeObject_TEMP_GEN_3;

    private NativeObject NativeObject_TEMP_GEN_4;

    static public final ImGuiViewport NULL = ImGuiViewport.native_new();

    public ImGuiViewport() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImGuiViewport.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiViewport(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiViewport native_new() {
        return new ImGuiViewport((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_deleteNative(this_addr);
    }

    public ImVec2 GetCenter() {
        long addr = internal_native_GetCenter_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_GetCenter_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_GetCenter_addr(this_addr);
    }

    public ImVec2 GetWorkCenter() {
        long addr = internal_native_GetWorkCenter_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_1;
    }

    public static long internal_native_GetWorkCenter_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_GetWorkCenter_addr(this_addr);
    }

    public NativeString GetDebugName() {
        long addr = internal_native_GetDebugName_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_0 == null)
            NativeString_TEMP_GEN_0 = NativeString.native_new();
        NativeString_TEMP_GEN_0.internal_reset(addr, false);
        return NativeString_TEMP_GEN_0;
    }

    public static long internal_native_GetDebugName_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_GetDebugName_addr(this_addr);
    }

    public int get_ID() {
        return internal_native_get_ID(native_address);
    }

    public static int internal_native_get_ID(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_ID(this_addr);
    }

    public void set_ID(int ID) {
        internal_native_set_ID(native_address, ID);
    }

    public static void internal_native_set_ID(long this_addr, int ID) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_ID(this_addr, ID);
    }

    public ImGuiViewportFlags get_Flags() {
        int value = internal_native_get_Flags(native_address);
        ImGuiViewportFlags[] values = ImGuiViewportFlags.values();
        for (int i = 0; i < values.length; i++) {
            ImGuiViewportFlags enumVal = values[i];
            if (enumVal != ImGuiViewportFlags.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ImGuiViewportFlags.CUSTOM.setValue(value);
    }

    public static int internal_native_get_Flags(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_Flags(this_addr);
    }

    public void set_Flags(ImGuiViewportFlags Flags) {
        internal_native_set_Flags(native_address, Flags.getValue());
    }

    public static void internal_native_set_Flags(long this_addr, int Flags) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_Flags(this_addr, Flags);
    }

    public ImVec2 get_Pos() {
        long addr = internal_native_get_Pos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_2 == null)
            ImVec2_TEMP_GEN_2 = ImVec2.native_new();
        ImVec2_TEMP_GEN_2.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_2;
    }

    public static long internal_native_get_Pos_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_Pos_addr(this_addr);
    }

    public void set_Pos(ImVec2 Pos) {
        internal_native_set_Pos(native_address, Pos.native_address);
    }

    public static void internal_native_set_Pos(long this_addr, long Pos_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_Pos(this_addr, Pos_addr);
    }

    public ImVec2 get_Size() {
        long addr = internal_native_get_Size_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_3 == null)
            ImVec2_TEMP_GEN_3 = ImVec2.native_new();
        ImVec2_TEMP_GEN_3.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_3;
    }

    public static long internal_native_get_Size_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_Size_addr(this_addr);
    }

    public void set_Size(ImVec2 Size) {
        internal_native_set_Size(native_address, Size.native_address);
    }

    public static void internal_native_set_Size(long this_addr, long Size_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_Size(this_addr, Size_addr);
    }

    public ImVec2 get_FramebufferScale() {
        long addr = internal_native_get_FramebufferScale_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_4 == null)
            ImVec2_TEMP_GEN_4 = ImVec2.native_new();
        ImVec2_TEMP_GEN_4.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_4;
    }

    public static long internal_native_get_FramebufferScale_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_FramebufferScale_addr(this_addr);
    }

    public void set_FramebufferScale(ImVec2 FramebufferScale) {
        internal_native_set_FramebufferScale(native_address, FramebufferScale.native_address);
    }

    public static void internal_native_set_FramebufferScale(long this_addr, long FramebufferScale_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_FramebufferScale(this_addr, FramebufferScale_addr);
    }

    public ImVec2 get_WorkPos() {
        long addr = internal_native_get_WorkPos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_5 == null)
            ImVec2_TEMP_GEN_5 = ImVec2.native_new();
        ImVec2_TEMP_GEN_5.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_5;
    }

    public static long internal_native_get_WorkPos_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_WorkPos_addr(this_addr);
    }

    public void set_WorkPos(ImVec2 WorkPos) {
        internal_native_set_WorkPos(native_address, WorkPos.native_address);
    }

    public static void internal_native_set_WorkPos(long this_addr, long WorkPos_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_WorkPos(this_addr, WorkPos_addr);
    }

    public ImVec2 get_WorkSize() {
        long addr = internal_native_get_WorkSize_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_6 == null)
            ImVec2_TEMP_GEN_6 = ImVec2.native_new();
        ImVec2_TEMP_GEN_6.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_6;
    }

    public static long internal_native_get_WorkSize_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_WorkSize_addr(this_addr);
    }

    public void set_WorkSize(ImVec2 WorkSize) {
        internal_native_set_WorkSize(native_address, WorkSize.native_address);
    }

    public static void internal_native_set_WorkSize(long this_addr, long WorkSize_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_WorkSize(this_addr, WorkSize_addr);
    }

    public float get_DpiScale() {
        return internal_native_get_DpiScale(native_address);
    }

    public static float internal_native_get_DpiScale(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_DpiScale(this_addr);
    }

    public void set_DpiScale(float DpiScale) {
        internal_native_set_DpiScale(native_address, DpiScale);
    }

    public static void internal_native_set_DpiScale(long this_addr, float DpiScale) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_DpiScale(this_addr, DpiScale);
    }

    public int get_ParentViewportId() {
        return internal_native_get_ParentViewportId(native_address);
    }

    public static int internal_native_get_ParentViewportId(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_ParentViewportId(this_addr);
    }

    public void set_ParentViewportId(int ParentViewportId) {
        internal_native_set_ParentViewportId(native_address, ParentViewportId);
    }

    public static void internal_native_set_ParentViewportId(long this_addr, int ParentViewportId) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_ParentViewportId(this_addr, ParentViewportId);
    }

    public ImGuiViewport get_ParentViewport() {
        long addr = internal_native_get_ParentViewport_addr(native_address);
        if (addr == 0)
            return ImGuiViewport.NULL;
        if (ImGuiViewport_TEMP_GEN_0 == null)
            ImGuiViewport_TEMP_GEN_0 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiViewport_TEMP_GEN_0;
    }

    public static long internal_native_get_ParentViewport_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_ParentViewport_addr(this_addr);
    }

    public ImDrawData get_DrawData() {
        long addr = internal_native_get_DrawData_addr(native_address);
        if (addr == 0)
            return ImDrawData.NULL;
        if (ImDrawData_TEMP_GEN_0 == null)
            ImDrawData_TEMP_GEN_0 = ImDrawData.native_new();
        ImDrawData_TEMP_GEN_0.internal_reset(addr, false);
        return ImDrawData_TEMP_GEN_0;
    }

    public static long internal_native_get_DrawData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_DrawData_addr(this_addr);
    }

    public void set_DrawData(ImDrawData DrawData) {
        internal_native_set_DrawData(native_address, DrawData.native_address);
    }

    public static void internal_native_set_DrawData(long this_addr, long DrawData_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_DrawData(this_addr, DrawData_addr);
    }

    public NativeObject get_RendererUserData() {
        long addr = internal_native_get_RendererUserData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_RendererUserData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_RendererUserData_addr(this_addr);
    }

    public void set_RendererUserData(NativeObject RendererUserData) {
        internal_native_set_RendererUserData(native_address, RendererUserData.native_void_address);
    }

    public static void internal_native_set_RendererUserData(long this_addr, long RendererUserData_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_RendererUserData(this_addr, RendererUserData_addr);
    }

    public NativeObject get_PlatformUserData() {
        long addr = internal_native_get_PlatformUserData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_1 == null)
            NativeObject_TEMP_GEN_1 = NativeObject.native_new();
        NativeObject_TEMP_GEN_1.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_1;
    }

    public static long internal_native_get_PlatformUserData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformUserData_addr(this_addr);
    }

    public void set_PlatformUserData(NativeObject PlatformUserData) {
        internal_native_set_PlatformUserData(native_address, PlatformUserData.native_void_address);
    }

    public static void internal_native_set_PlatformUserData(long this_addr, long PlatformUserData_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformUserData(this_addr, PlatformUserData_addr);
    }

    public NativeObject get_PlatformIconData() {
        long addr = internal_native_get_PlatformIconData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_2 == null)
            NativeObject_TEMP_GEN_2 = NativeObject.native_new();
        NativeObject_TEMP_GEN_2.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_2;
    }

    public static long internal_native_get_PlatformIconData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformIconData_addr(this_addr);
    }

    public void set_PlatformIconData(NativeObject PlatformIconData) {
        internal_native_set_PlatformIconData(native_address, PlatformIconData.native_void_address);
    }

    public static void internal_native_set_PlatformIconData(long this_addr, long PlatformIconData_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformIconData(this_addr, PlatformIconData_addr);
    }

    public NativeObject get_PlatformHandle() {
        long addr = internal_native_get_PlatformHandle_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_3 == null)
            NativeObject_TEMP_GEN_3 = NativeObject.native_new();
        NativeObject_TEMP_GEN_3.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_3;
    }

    public static long internal_native_get_PlatformHandle_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformHandle_addr(this_addr);
    }

    public void set_PlatformHandle(NativeObject PlatformHandle) {
        internal_native_set_PlatformHandle(native_address, PlatformHandle.native_void_address);
    }

    public static void internal_native_set_PlatformHandle(long this_addr, long PlatformHandle_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformHandle(this_addr, PlatformHandle_addr);
    }

    public NativeObject get_PlatformHandleRaw() {
        long addr = internal_native_get_PlatformHandleRaw_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_4 == null)
            NativeObject_TEMP_GEN_4 = NativeObject.native_new();
        NativeObject_TEMP_GEN_4.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_4;
    }

    public static long internal_native_get_PlatformHandleRaw_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformHandleRaw_addr(this_addr);
    }

    public void set_PlatformHandleRaw(NativeObject PlatformHandleRaw) {
        internal_native_set_PlatformHandleRaw(native_address, PlatformHandleRaw.native_void_address);
    }

    public static void internal_native_set_PlatformHandleRaw(long this_addr, long PlatformHandleRaw_addr) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformHandleRaw(this_addr, PlatformHandleRaw_addr);
    }

    public boolean get_PlatformWindowCreated() {
        return internal_native_get_PlatformWindowCreated(native_address);
    }

    public static boolean internal_native_get_PlatformWindowCreated(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformWindowCreated(this_addr);
    }

    public void set_PlatformWindowCreated(boolean PlatformWindowCreated) {
        internal_native_set_PlatformWindowCreated(native_address, PlatformWindowCreated);
    }

    public static void internal_native_set_PlatformWindowCreated(long this_addr, boolean PlatformWindowCreated) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformWindowCreated(this_addr, PlatformWindowCreated);
    }

    public boolean get_PlatformRequestMove() {
        return internal_native_get_PlatformRequestMove(native_address);
    }

    public static boolean internal_native_get_PlatformRequestMove(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformRequestMove(this_addr);
    }

    public void set_PlatformRequestMove(boolean PlatformRequestMove) {
        internal_native_set_PlatformRequestMove(native_address, PlatformRequestMove);
    }

    public static void internal_native_set_PlatformRequestMove(long this_addr, boolean PlatformRequestMove) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformRequestMove(this_addr, PlatformRequestMove);
    }

    public boolean get_PlatformRequestResize() {
        return internal_native_get_PlatformRequestResize(native_address);
    }

    public static boolean internal_native_get_PlatformRequestResize(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformRequestResize(this_addr);
    }

    public void set_PlatformRequestResize(boolean PlatformRequestResize) {
        internal_native_set_PlatformRequestResize(native_address, PlatformRequestResize);
    }

    public static void internal_native_set_PlatformRequestResize(long this_addr, boolean PlatformRequestResize) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformRequestResize(this_addr, PlatformRequestResize);
    }

    public boolean get_PlatformRequestClose() {
        return internal_native_get_PlatformRequestClose(native_address);
    }

    public static boolean internal_native_get_PlatformRequestClose(long this_addr) {
        return imgui.natives.JNI_ImGuiViewport.internal_native_get_PlatformRequestClose(this_addr);
    }

    public void set_PlatformRequestClose(boolean PlatformRequestClose) {
        internal_native_set_PlatformRequestClose(native_address, PlatformRequestClose);
    }

    public static void internal_native_set_PlatformRequestClose(long this_addr, boolean PlatformRequestClose) {
        imgui.natives.JNI_ImGuiViewport.internal_native_set_PlatformRequestClose(this_addr, PlatformRequestClose);
    }
}
