/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiSelectionBasicStorageIterator extends NativeObject {

    static public final ImGuiSelectionBasicStorageIterator NULL = ImGuiSelectionBasicStorageIterator.native_new();

    public ImGuiSelectionBasicStorageIterator() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImGuiSelectionBasicStorageIterator.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiSelectionBasicStorageIterator(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSelectionBasicStorageIterator native_new() {
        return new ImGuiSelectionBasicStorageIterator((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorageIterator.internal_native_deleteNative(this_addr);
    }

    public void Reset() {
        internal_native_Reset(native_address);
    }

    public static void internal_native_Reset(long this_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorageIterator.internal_native_Reset(this_addr);
    }

    public boolean Next(ImGuiSelectionBasicStorage storage) {
        return internal_native_Next(native_address, storage.native_address);
    }

    public static boolean internal_native_Next(long this_addr, long storage_addr) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorageIterator.internal_native_Next(this_addr, storage_addr);
    }

    public int GetID() {
        return internal_native_GetID(native_address);
    }

    public static int internal_native_GetID(long this_addr) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorageIterator.internal_native_GetID(this_addr);
    }
}
