/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiSelectionBasicStorage extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    static public final ImGuiSelectionBasicStorage NULL = ImGuiSelectionBasicStorage.native_new();

    public ImGuiSelectionBasicStorage() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiSelectionBasicStorage(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSelectionBasicStorage native_new() {
        return new ImGuiSelectionBasicStorage((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_deleteNative(this_addr);
    }

    public void ApplyRequests(ImGuiMultiSelectIO ms_io) {
        internal_native_ApplyRequests(native_address, ms_io.native_address);
    }

    public static void internal_native_ApplyRequests(long this_addr, long ms_io_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_ApplyRequests(this_addr, ms_io_addr);
    }

    public boolean Contains(int id) {
        return internal_native_Contains(native_address, id);
    }

    public static boolean internal_native_Contains(long this_addr, int id) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_Contains(this_addr, id);
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    public static void internal_native_Clear(long this_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_Clear(this_addr);
    }

    public void Swap(ImGuiSelectionBasicStorage other) {
        internal_native_Swap(native_address, other.native_address);
    }

    public static void internal_native_Swap(long this_addr, long other_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_Swap(this_addr, other_addr);
    }

    public void SetItemSelected(int id, boolean selected) {
        internal_native_SetItemSelected(native_address, id, selected);
    }

    public static void internal_native_SetItemSelected(long this_addr, int id, boolean selected) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_SetItemSelected(this_addr, id, selected);
    }

    public int GetStorageIdFromIndex(int index) {
        return internal_native_GetStorageIdFromIndex(native_address, index);
    }

    public static int internal_native_GetStorageIdFromIndex(long this_addr, int index) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_GetStorageIdFromIndex(this_addr, index);
    }

    public int get_Size() {
        return internal_native_get_Size(native_address);
    }

    public static int internal_native_get_Size(long this_addr) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_get_Size(this_addr);
    }

    public boolean get_PreserveOrder() {
        return internal_native_get_PreserveOrder(native_address);
    }

    public static boolean internal_native_get_PreserveOrder(long this_addr) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_get_PreserveOrder(this_addr);
    }

    public void set_PreserveOrder(boolean PreserveOrder) {
        internal_native_set_PreserveOrder(native_address, PreserveOrder);
    }

    public static void internal_native_set_PreserveOrder(long this_addr, boolean PreserveOrder) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_set_PreserveOrder(this_addr, PreserveOrder);
    }

    public NativeObject get_UserData() {
        long addr = internal_native_get_UserData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_UserData_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_get_UserData_addr(this_addr);
    }

    public void set_UserData(NativeObject UserData) {
        internal_native_set_UserData(native_address, UserData.native_void_address);
    }

    public static void internal_native_set_UserData(long this_addr, long UserData_addr) {
        imgui.natives.JNI_ImGuiSelectionBasicStorage.internal_native_set_UserData(this_addr, UserData_addr);
    }
}
