/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiPlatformMonitor extends NativeObject {

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    private ImVec2 ImVec2_TEMP_GEN_2;

    private ImVec2 ImVec2_TEMP_GEN_3;

    private NativeObject NativeObject_TEMP_GEN_0;

    static public final ImGuiPlatformMonitor NULL = ImGuiPlatformMonitor.native_new();

    public ImGuiPlatformMonitor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiPlatformMonitor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiPlatformMonitor native_new() {
        return new ImGuiPlatformMonitor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_deleteNative(this_addr);
    }

    public ImVec2 get_MainPos() {
        long addr = internal_native_get_MainPos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_get_MainPos_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_get_MainPos_addr(this_addr);
    }

    public void set_MainPos(ImVec2 MainPos) {
        internal_native_set_MainPos(native_address, MainPos.native_address);
    }

    public static void internal_native_set_MainPos(long this_addr, long MainPos_addr) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_set_MainPos(this_addr, MainPos_addr);
    }

    public ImVec2 get_MainSize() {
        long addr = internal_native_get_MainSize_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_1;
    }

    public static long internal_native_get_MainSize_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_get_MainSize_addr(this_addr);
    }

    public void set_MainSize(ImVec2 MainSize) {
        internal_native_set_MainSize(native_address, MainSize.native_address);
    }

    public static void internal_native_set_MainSize(long this_addr, long MainSize_addr) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_set_MainSize(this_addr, MainSize_addr);
    }

    public ImVec2 get_WorkPos() {
        long addr = internal_native_get_WorkPos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_2 == null)
            ImVec2_TEMP_GEN_2 = ImVec2.native_new();
        ImVec2_TEMP_GEN_2.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_2;
    }

    public static long internal_native_get_WorkPos_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_get_WorkPos_addr(this_addr);
    }

    public void set_WorkPos(ImVec2 WorkPos) {
        internal_native_set_WorkPos(native_address, WorkPos.native_address);
    }

    public static void internal_native_set_WorkPos(long this_addr, long WorkPos_addr) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_set_WorkPos(this_addr, WorkPos_addr);
    }

    public ImVec2 get_WorkSize() {
        long addr = internal_native_get_WorkSize_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_3 == null)
            ImVec2_TEMP_GEN_3 = ImVec2.native_new();
        ImVec2_TEMP_GEN_3.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_3;
    }

    public static long internal_native_get_WorkSize_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_get_WorkSize_addr(this_addr);
    }

    public void set_WorkSize(ImVec2 WorkSize) {
        internal_native_set_WorkSize(native_address, WorkSize.native_address);
    }

    public static void internal_native_set_WorkSize(long this_addr, long WorkSize_addr) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_set_WorkSize(this_addr, WorkSize_addr);
    }

    public float get_DpiScale() {
        return internal_native_get_DpiScale(native_address);
    }

    public static float internal_native_get_DpiScale(long this_addr) {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_get_DpiScale(this_addr);
    }

    public void set_DpiScale(float DpiScale) {
        internal_native_set_DpiScale(native_address, DpiScale);
    }

    public static void internal_native_set_DpiScale(long this_addr, float DpiScale) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_set_DpiScale(this_addr, DpiScale);
    }

    public NativeObject get_PlatformHandle() {
        long addr = internal_native_get_PlatformHandle_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_PlatformHandle_addr(long this_addr) {
        return imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_get_PlatformHandle_addr(this_addr);
    }

    public void set_PlatformHandle(NativeObject PlatformHandle) {
        internal_native_set_PlatformHandle(native_address, PlatformHandle.native_void_address);
    }

    public static void internal_native_set_PlatformHandle(long this_addr, long PlatformHandle_addr) {
        imgui.natives.JNI_ImGuiPlatformMonitor.internal_native_set_PlatformHandle(this_addr, PlatformHandle_addr);
    }
}
