/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImVectorImGuiViewportPtr extends NativeObject {

    private ImGuiViewport ImGuiViewport_TEMP_GEN_0;

    private NativeObject NativeObject_TEMP_GEN_0;

    static public final ImVectorImGuiViewportPtr NULL = ImVectorImGuiViewportPtr.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImVectorImGuiViewportPtr(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImVectorImGuiViewportPtr native_new() {
        return new ImVectorImGuiViewportPtr((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.natives.JNI_ImVectorImGuiViewportPtr.internal_native_deleteNative(this_addr);
    }

    public int size() {
        return internal_native_size(native_address);
    }

    public static int internal_native_size(long this_addr) {
        return imgui.natives.JNI_ImVectorImGuiViewportPtr.internal_native_size(this_addr);
    }

    public ImGuiViewport getData(int index) {
        long addr = internal_native_getData_addr(native_address, index);
        if (addr == 0)
            return ImGuiViewport.NULL;
        if (ImGuiViewport_TEMP_GEN_0 == null)
            ImGuiViewport_TEMP_GEN_0 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiViewport_TEMP_GEN_0;
    }

    public static long internal_native_getData_addr(long this_addr, int index) {
        return imgui.natives.JNI_ImVectorImGuiViewportPtr.internal_native_getData_addr(this_addr, index);
    }

    public NativeObject get_Data() {
        long addr = internal_native_get_Data_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_Data_addr(long this_addr) {
        return imgui.natives.JNI_ImVectorImGuiViewportPtr.internal_native_get_Data_addr(this_addr);
    }
}
