/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.ImVec2;

public final class TextDiff extends NativeObject {

    static public final TextDiff NULL = TextDiff.native_new();

    public TextDiff() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TextDiff(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static TextDiff native_new() {
        return new TextDiff((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_deleteNative(this_addr);
    }

    public void SetSideBySideMode(boolean value) {
        internal_native_SetSideBySideMode(native_address, value);
    }

    public static void internal_native_SetSideBySideMode(long this_addr, boolean value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetSideBySideMode(this_addr, value);
    }

    public boolean GetSideBySideMode() {
        return internal_native_GetSideBySideMode(native_address);
    }

    public static boolean internal_native_GetSideBySideMode(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_GetSideBySideMode(this_addr);
    }

    public void SetTabSize(long value) {
        internal_native_SetTabSize(native_address, value);
    }

    public static void internal_native_SetTabSize(long this_addr, long value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetTabSize(this_addr, value);
    }

    public long GetTabSize() {
        return internal_native_GetTabSize(native_address);
    }

    public static long internal_native_GetTabSize(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_GetTabSize(this_addr);
    }

    public void SetLineSpacing(float value) {
        internal_native_SetLineSpacing(native_address, value);
    }

    public static void internal_native_SetLineSpacing(long this_addr, float value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetLineSpacing(this_addr, value);
    }

    public float GetLineSpacing() {
        return internal_native_GetLineSpacing(native_address);
    }

    public static float internal_native_GetLineSpacing(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_GetLineSpacing(this_addr);
    }

    public void SetWordWrapEnabled(boolean value) {
        internal_native_SetWordWrapEnabled(native_address, value);
    }

    public static void internal_native_SetWordWrapEnabled(long this_addr, boolean value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetWordWrapEnabled(this_addr, value);
    }

    public boolean IsWordWrapEnabled() {
        return internal_native_IsWordWrapEnabled(native_address);
    }

    public static boolean internal_native_IsWordWrapEnabled(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_IsWordWrapEnabled(this_addr);
    }

    public void SetShowWhitespacesEnabled(boolean value) {
        internal_native_SetShowWhitespacesEnabled(native_address, value);
    }

    public static void internal_native_SetShowWhitespacesEnabled(long this_addr, boolean value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetShowWhitespacesEnabled(this_addr, value);
    }

    public boolean IsShowWhitespacesEnabled() {
        return internal_native_IsShowWhitespacesEnabled(native_address);
    }

    public static boolean internal_native_IsShowWhitespacesEnabled(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_IsShowWhitespacesEnabled(this_addr);
    }

    public void SetShowSpacesEnabled(boolean value) {
        internal_native_SetShowSpacesEnabled(native_address, value);
    }

    public static void internal_native_SetShowSpacesEnabled(long this_addr, boolean value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetShowSpacesEnabled(this_addr, value);
    }

    public boolean IsShowSpacesEnabled() {
        return internal_native_IsShowSpacesEnabled(native_address);
    }

    public static boolean internal_native_IsShowSpacesEnabled(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_IsShowSpacesEnabled(this_addr);
    }

    public void SetShowTabsEnabled(boolean value) {
        internal_native_SetShowTabsEnabled(native_address, value);
    }

    public static void internal_native_SetShowTabsEnabled(long this_addr, boolean value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetShowTabsEnabled(this_addr, value);
    }

    public boolean IsShowTabsEnabled() {
        return internal_native_IsShowTabsEnabled(native_address);
    }

    public static boolean internal_native_IsShowTabsEnabled(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_IsShowTabsEnabled(this_addr);
    }

    public void SetShowScrollbarMiniMapEnabled(boolean value) {
        internal_native_SetShowScrollbarMiniMapEnabled(native_address, value);
    }

    public static void internal_native_SetShowScrollbarMiniMapEnabled(long this_addr, boolean value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetShowScrollbarMiniMapEnabled(this_addr, value);
    }

    public boolean IsShowScrollbarMiniMapEnabled() {
        return internal_native_IsShowScrollbarMiniMapEnabled(native_address);
    }

    public static boolean internal_native_IsShowScrollbarMiniMapEnabled(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_IsShowScrollbarMiniMapEnabled(this_addr);
    }

    public void SetLanguage(TextEditorLanguage language) {
        internal_native_SetLanguage(native_address, language.getValue());
    }

    public static void internal_native_SetLanguage(long this_addr, int language) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetLanguage(this_addr, language);
    }

    public TextEditorLanguage GetLanguage() {
        int value = internal_native_GetLanguage(native_address);
        TextEditorLanguage[] values = TextEditorLanguage.values();
        for (int i = 0; i < values.length; i++) {
            TextEditorLanguage enumVal = values[i];
            if (enumVal != TextEditorLanguage.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return TextEditorLanguage.CUSTOM.setValue(value);
    }

    public static int internal_native_GetLanguage(long this_addr) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_GetLanguage(this_addr);
    }

    public void SetColors(int addedColor, int deletedColor) {
        internal_native_SetColors(native_address, addedColor, deletedColor);
    }

    public static void internal_native_SetColors(long this_addr, int addedColor, int deletedColor) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetColors(this_addr, addedColor, deletedColor);
    }

    public void SetPalette(TextEditorPalette palette) {
        internal_native_SetPalette(native_address, palette.getValue());
    }

    public static void internal_native_SetPalette(long this_addr, int palette) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetPalette(this_addr, palette);
    }

    public void SetPaletteColor(TextEditorColor color, int value) {
        internal_native_SetPaletteColor(native_address, color.getValue(), value);
    }

    public static void internal_native_SetPaletteColor(long this_addr, int color, int value) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetPaletteColor(this_addr, color, value);
    }

    public int GetPaletteColor(TextEditorColor color) {
        return internal_native_GetPaletteColor(native_address, color.getValue());
    }

    public static int internal_native_GetPaletteColor(long this_addr, int color) {
        return imgui.extension.textedit.natives.JNI_TextDiff.internal_native_GetPaletteColor(this_addr, color);
    }

    public void SetFocus() {
        internal_native_SetFocus(native_address);
    }

    public static void internal_native_SetFocus(long this_addr) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetFocus(this_addr);
    }

    public void SetText(String left, String right) {
        internal_native_SetText(native_address, left, right);
    }

    public static void internal_native_SetText(long this_addr, String left, String right) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_SetText(this_addr, left, right);
    }

    public void Render(String title, ImVec2 size, int childFlags, int windowFlags) {
        internal_native_Render(native_address, title, size.native_address, childFlags, windowFlags);
    }

    public static void internal_native_Render(long this_addr, String title, long size_addr, int childFlags, int windowFlags) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_Render(this_addr, title, size_addr, childFlags, windowFlags);
    }

    public void Render(String title, ImVec2 size, int childFlags) {
        internal_native_Render(native_address, title, size.native_address, childFlags);
    }

    public static void internal_native_Render(long this_addr, String title, long size_addr, int childFlags) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_Render(this_addr, title, size_addr, childFlags);
    }

    public void Render(String title, ImVec2 size) {
        internal_native_Render(native_address, title, size.native_address);
    }

    public static void internal_native_Render(long this_addr, String title, long size_addr) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_Render(this_addr, title, size_addr);
    }

    public void Render(String title) {
        internal_native_Render(native_address, title);
    }

    public static void internal_native_Render(long this_addr, String title) {
        imgui.extension.textedit.natives.JNI_TextDiff.internal_native_Render(this_addr, title);
    }
}
