/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class ImDrawData extends NativeObject {

    private ImVectorImTextureDataPtr ImVectorImTextureDataPtr_TEMP_GEN_0;

    private ImVectorImDrawListPtr ImVectorImDrawListPtr_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    private ImVec2 ImVec2_TEMP_GEN_2;

    private ImGuiViewport ImGuiViewport_TEMP_GEN_0;

    public final static ImDrawData NULL = native_new();

    public static ImDrawData native_new() {
        return new ImDrawData((byte) 0, (char) 0);
    }

    private ImDrawData(byte b, char c) {
    }

    public ImDrawData() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    public static void internal_native_Clear(long this_addr) {
        try {
            FFMHandles.internal_native_Clear__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void AddDrawList(ImDrawList draw_list) {
        internal_native_AddDrawList(native_address, draw_list.native_address);
    }

    public static void internal_native_AddDrawList(long this_addr, long draw_list_addr) {
        try {
            FFMHandles.internal_native_AddDrawList__JJ.invokeExact(this_addr, draw_list_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void DeIndexAllBuffers() {
        internal_native_DeIndexAllBuffers(native_address);
    }

    public static void internal_native_DeIndexAllBuffers(long this_addr) {
        try {
            FFMHandles.internal_native_DeIndexAllBuffers__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ScaleClipRects(ImVec2 fb_scale) {
        internal_native_ScaleClipRects(native_address, fb_scale.native_address);
    }

    public static void internal_native_ScaleClipRects(long this_addr, long fb_scale_addr) {
        try {
            FFMHandles.internal_native_ScaleClipRects__JJ.invokeExact(this_addr, fb_scale_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_FrameCount() {
        return internal_native_get_FrameCount(native_address);
    }

    public static int internal_native_get_FrameCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_FrameCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_TotalIdxCount() {
        return internal_native_get_TotalIdxCount(native_address);
    }

    public static int internal_native_get_TotalIdxCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_TotalIdxCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_TotalVtxCount() {
        return internal_native_get_TotalVtxCount(native_address);
    }

    public static int internal_native_get_TotalVtxCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_TotalVtxCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_Valid() {
        return internal_native_get_Valid(native_address);
    }

    public static boolean internal_native_get_Valid(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_Valid__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVectorImTextureDataPtr get_Textures() {
        long addr = internal_native_get_Textures_addr(native_address);
        if (addr == 0)
            return ImVectorImTextureDataPtr.NULL;
        if (ImVectorImTextureDataPtr_TEMP_GEN_0 == null)
            ImVectorImTextureDataPtr_TEMP_GEN_0 = ImVectorImTextureDataPtr.native_new();
        ImVectorImTextureDataPtr_TEMP_GEN_0.internal_reset(addr, false);
        return ImVectorImTextureDataPtr_TEMP_GEN_0;
    }

    public static long internal_native_get_Textures_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_Textures_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVectorImDrawListPtr get_CmdLists() {
        long addr = internal_native_get_CmdLists_addr(native_address);
        if (addr == 0)
            return ImVectorImDrawListPtr.NULL;
        if (ImVectorImDrawListPtr_TEMP_GEN_0 == null)
            ImVectorImDrawListPtr_TEMP_GEN_0 = ImVectorImDrawListPtr.native_new();
        ImVectorImDrawListPtr_TEMP_GEN_0.internal_reset(addr, false);
        return ImVectorImDrawListPtr_TEMP_GEN_0;
    }

    public static long internal_native_get_CmdLists_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_CmdLists_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVec2 get_DisplayPos() {
        long addr = internal_native_get_DisplayPos_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_get_DisplayPos_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_DisplayPos_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVec2 get_DisplaySize() {
        long addr = internal_native_get_DisplaySize_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_1;
    }

    public static long internal_native_get_DisplaySize_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_DisplaySize_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVec2 get_FramebufferScale() {
        long addr = internal_native_get_FramebufferScale_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_2 == null)
            ImVec2_TEMP_GEN_2 = ImVec2.native_new();
        ImVec2_TEMP_GEN_2.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_2;
    }

    public static long internal_native_get_FramebufferScale_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_FramebufferScale_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImGuiViewport get_OwnerViewport() {
        long addr = internal_native_get_OwnerViewport_addr(native_address);
        if (addr == 0)
            return ImGuiViewport.NULL;
        if (ImGuiViewport_TEMP_GEN_0 == null)
            ImGuiViewport_TEMP_GEN_0 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_GEN_0.internal_reset(addr, false);
        return ImGuiViewport_TEMP_GEN_0;
    }

    public static long internal_native_get_OwnerViewport_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_OwnerViewport_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawdata_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Clear__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawdata_clear", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_AddDrawList__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawdata_adddrawlist", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_DeIndexAllBuffers__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawdata_deindexallbuffers", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ScaleClipRects__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawdata_scalecliprects", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_FrameCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_framecount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_TotalIdxCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_totalidxcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_TotalVtxCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_totalvtxcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_Valid__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_valid", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_Textures_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_textures_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_CmdLists_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_cmdlists_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_DisplayPos_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_displaypos_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_DisplaySize_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_displaysize_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_FramebufferScale_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_framebufferscale_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_OwnerViewport_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawdata_get_ownerviewport_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
