/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImDrawCallbackFunction extends NativeObject {

    static private ImDrawList ImDrawList_TEMP_STATIC_GEN_0;

    static private ImDrawCmd ImDrawCmd_TEMP_STATIC_GEN_0;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onDraw = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onDraw = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final ImDrawCallbackFunction NULL = ImDrawCallbackFunction.native_new();

    @Deprecated()
    protected ImDrawCallbackFunction(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImDrawCallbackFunction native_new() {
        return new ImDrawCallbackFunction((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImDrawCallbackFunction() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onDraw = callbackLookup.findVirtual(ImDrawCallbackFunction.class, "internal_onDraw", callbackMethodType_onDraw).bindTo(this);
            upcallStub_onDraw = callbackLinker.upcallStub(mh_onDraw, callbackDescriptor_onDraw, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onDraw.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onDraw(ImDrawList parent_list, ImDrawCmd draw_cmd) {
    }

    private void internal_onDraw(long parent_list_addr, long draw_cmd_addr) {
        if (ImDrawList_TEMP_STATIC_GEN_0 == null)
            ImDrawList_TEMP_STATIC_GEN_0 = ImDrawList.native_new();
        ImDrawList_TEMP_STATIC_GEN_0.internal_reset(parent_list_addr, false);
        if (ImDrawCmd_TEMP_STATIC_GEN_0 == null)
            ImDrawCmd_TEMP_STATIC_GEN_0 = ImDrawCmd.native_new();
        ImDrawCmd_TEMP_STATIC_GEN_0.internal_reset(draw_cmd_addr, false);
        onDraw(ImDrawList_TEMP_STATIC_GEN_0, ImDrawCmd_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onDraw;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onDraw = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onDraw_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, onDraw_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawcallbackfunction_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imdrawcallbackfunction_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imdrawcallbackfunction_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
