/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class ImFontAtlasRect extends NativeObject {

    private ImVec2 ImVec2_TEMP_GEN_0;

    private ImVec2 ImVec2_TEMP_GEN_1;

    static public final ImFontAtlasRect NULL = ImFontAtlasRect.native_new();

    public ImFontAtlasRect() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImFontAtlasRect(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImFontAtlasRect native_new() {
        return new ImFontAtlasRect((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_x() {
        return internal_native_get_x(native_address);
    }

    public static short internal_native_get_x(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_x__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_y() {
        return internal_native_get_y(native_address);
    }

    public static short internal_native_get_y(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_y__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_w() {
        return internal_native_get_w(native_address);
    }

    public static short internal_native_get_w(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_w__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_h() {
        return internal_native_get_h(native_address);
    }

    public static short internal_native_get_h(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_h__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVec2 get_uv0() {
        long addr = internal_native_get_uv0_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_0 == null)
            ImVec2_TEMP_GEN_0 = ImVec2.native_new();
        ImVec2_TEMP_GEN_0.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_0;
    }

    public static long internal_native_get_uv0_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_uv0_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImVec2 get_uv1() {
        long addr = internal_native_get_uv1_addr(native_address);
        if (addr == 0)
            return ImVec2.NULL;
        if (ImVec2_TEMP_GEN_1 == null)
            ImVec2_TEMP_GEN_1 = ImVec2.native_new();
        ImVec2_TEMP_GEN_1.internal_reset(addr, false);
        return ImVec2_TEMP_GEN_1;
    }

    public static long internal_native_get_uv1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_uv1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imfontatlasrect_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_x__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_get_x", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_y__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_get_y", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_w__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_get_w", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_h__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_get_h", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_uv0_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_get_uv0_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_uv1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imfontatlasrect_get_uv1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
