/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiSelectionExternalStorageAdapter extends NativeObject {

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onSetItemSelected = java.lang.invoke.MethodType.methodType(void.class, int.class, boolean.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetItemSelected = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_BOOLEAN);

    static public final ImGuiSelectionExternalStorageAdapter NULL = ImGuiSelectionExternalStorageAdapter.native_new();

    @Deprecated()
    protected ImGuiSelectionExternalStorageAdapter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSelectionExternalStorageAdapter native_new() {
        return new ImGuiSelectionExternalStorageAdapter((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void Install(ImGuiSelectionExternalStorage storage, ImGuiSelectionExternalStorageAdapter adapter) {
        internal_native_Install(storage.native_address, adapter.native_address);
    }

    public static void internal_native_Install(long storage_addr, long adapter_addr) {
        try {
            FFMHandles.internal_native_Install__JJ.invokeExact(storage_addr, adapter_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void Clear(ImGuiSelectionExternalStorage storage) {
        internal_native_Clear(storage.native_address);
    }

    public static void internal_native_Clear(long storage_addr) {
        try {
            FFMHandles.internal_native_Clear__J.invokeExact(storage_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImGuiSelectionExternalStorageAdapter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onSetItemSelected = callbackLookup.findVirtual(ImGuiSelectionExternalStorageAdapter.class, "internal_onSetItemSelected", callbackMethodType_onSetItemSelected).bindTo(this);
            upcallStub_onSetItemSelected = callbackLinker.upcallStub(mh_onSetItemSelected, callbackDescriptor_onSetItemSelected, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onSetItemSelected.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onSetItemSelected(int index, boolean selected) {
    }

    private void internal_onSetItemSelected(int index, boolean selected) {
        onSetItemSelected(index, selected);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onSetItemSelected;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onSetItemSelected = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onSetItemSelected_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, onSetItemSelected_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiselectionexternalstorageadapter_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Install__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiselectionexternalstorageadapter_install", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Clear__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiselectionexternalstorageadapter_clear", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguiselectionexternalstorageadapter_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiselectionexternalstorageadapter_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
