/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiViewportPlatformCallbacks extends NativeObject {

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_0;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_1;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_2;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_3;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_4;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_5;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_6;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_7;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_8;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_9;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_10;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_11;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_12;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_13;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_14;

    static private NativeString NativeString_TEMP_STATIC_GEN_0;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_15;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_16;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_17;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_18;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_19;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_20;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_21;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_22;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_23;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_24;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_25;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_0;

    static private NativeObject NativeObject_TEMP_STATIC_GEN_1;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_26;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_27;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_28;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_29;

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_30;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onCreateWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onCreateWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onDestroyWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onDestroyWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onShowWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onShowWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSetWindowPos = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class, float.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetWindowPos = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowPosX = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowPosX = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowPosY = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowPosY = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSetWindowSize = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class, float.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetWindowSize = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowSizeX = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowSizeX = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowSizeY = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowSizeY = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowFramebufferScaleX = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowFramebufferScaleX = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowFramebufferScaleY = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowFramebufferScaleY = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSetWindowFocus = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetWindowFocus = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowFocus = java.lang.invoke.MethodType.methodType(boolean.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowFocus = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowMinimized = java.lang.invoke.MethodType.methodType(boolean.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowMinimized = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSetWindowTitle = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetWindowTitle = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSetWindowAlpha = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetWindowAlpha = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT);

    private static final java.lang.invoke.MethodType callbackMethodType_onUpdateWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onUpdateWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onRenderWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onRenderWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onSwapBuffers = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSwapBuffers = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowDpiScale = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowDpiScale = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onChangedViewport = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onChangedViewport = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowWorkAreaInsetX = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowWorkAreaInsetX = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowWorkAreaInsetY = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowWorkAreaInsetY = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowWorkAreaInsetZ = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowWorkAreaInsetZ = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onGetWindowWorkAreaInsetW = java.lang.invoke.MethodType.methodType(float.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onGetWindowWorkAreaInsetW = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onCreateVkSurface = java.lang.invoke.MethodType.methodType(int.class, long.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onCreateVkSurface = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_INT, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onRendererCreateWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onRendererCreateWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onRendererDestroyWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onRendererDestroyWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onRendererSetWindowSize = java.lang.invoke.MethodType.methodType(void.class, long.class, float.class, float.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onRendererSetWindowSize = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_FLOAT, java.lang.foreign.ValueLayout.JAVA_FLOAT);

    private static final java.lang.invoke.MethodType callbackMethodType_onRendererRenderWindow = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onRendererRenderWindow = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    private static final java.lang.invoke.MethodType callbackMethodType_onRendererSwapBuffers = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onRendererSwapBuffers = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final ImGuiViewportPlatformCallbacks NULL = ImGuiViewportPlatformCallbacks.native_new();

    @Deprecated()
    protected ImGuiViewportPlatformCallbacks(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiViewportPlatformCallbacks native_new() {
        return new ImGuiViewportPlatformCallbacks((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void setCallbacks(ImGuiPlatformIO io, ImGuiViewportPlatformCallbacks callbacks) {
        internal_native_setCallbacks(io.native_address, callbacks.native_address);
    }

    public static void internal_native_setCallbacks(long io_addr, long callbacks_addr) {
        try {
            FFMHandles.internal_native_setCallbacks__JJ.invokeExact(io_addr, callbacks_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void clearCallbacks(ImGuiPlatformIO io) {
        internal_native_clearCallbacks(io.native_address);
    }

    public static void internal_native_clearCallbacks(long io_addr) {
        try {
            FFMHandles.internal_native_clearCallbacks__J.invokeExact(io_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void setMainMonitor(ImGuiPlatformIO io, float mainX, float mainY, float mainWidth, float mainHeight, float workX, float workY, float workWidth, float workHeight, float dpiScale) {
        internal_native_setMainMonitor(io.native_address, mainX, mainY, mainWidth, mainHeight, workX, workY, workWidth, workHeight, dpiScale);
    }

    public static void internal_native_setMainMonitor(long io_addr, float mainX, float mainY, float mainWidth, float mainHeight, float workX, float workY, float workWidth, float workHeight, float dpiScale) {
        try {
            FFMHandles.internal_native_setMainMonitor__JFFFFFFFFF.invokeExact(io_addr, mainX, mainY, mainWidth, mainHeight, workX, workY, workWidth, workHeight, dpiScale);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void setMainViewportPlatformHandle(ImGuiViewport viewport, ImGuiViewportPlatformCallbacks callbacks) {
        internal_native_setMainViewportPlatformHandle(viewport.native_address, callbacks.native_address);
    }

    public static void internal_native_setMainViewportPlatformHandle(long viewport_addr, long callbacks_addr) {
        try {
            FFMHandles.internal_native_setMainViewportPlatformHandle__JJ.invokeExact(viewport_addr, callbacks_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void clearViewportPlatformHandles(ImGuiViewport viewport) {
        internal_native_clearViewportPlatformHandles(viewport.native_address);
    }

    public static void internal_native_clearViewportPlatformHandles(long viewport_addr) {
        try {
            FFMHandles.internal_native_clearViewportPlatformHandles__J.invokeExact(viewport_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImGuiViewportPlatformCallbacks() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onCreateWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onCreateWindow", callbackMethodType_onCreateWindow).bindTo(this);
            upcallStub_onCreateWindow = callbackLinker.upcallStub(mh_onCreateWindow, callbackDescriptor_onCreateWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onDestroyWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onDestroyWindow", callbackMethodType_onDestroyWindow).bindTo(this);
            upcallStub_onDestroyWindow = callbackLinker.upcallStub(mh_onDestroyWindow, callbackDescriptor_onDestroyWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onShowWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onShowWindow", callbackMethodType_onShowWindow).bindTo(this);
            upcallStub_onShowWindow = callbackLinker.upcallStub(mh_onShowWindow, callbackDescriptor_onShowWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onSetWindowPos = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onSetWindowPos", callbackMethodType_onSetWindowPos).bindTo(this);
            upcallStub_onSetWindowPos = callbackLinker.upcallStub(mh_onSetWindowPos, callbackDescriptor_onSetWindowPos, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowPosX = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowPosX", callbackMethodType_onGetWindowPosX).bindTo(this);
            upcallStub_onGetWindowPosX = callbackLinker.upcallStub(mh_onGetWindowPosX, callbackDescriptor_onGetWindowPosX, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowPosY = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowPosY", callbackMethodType_onGetWindowPosY).bindTo(this);
            upcallStub_onGetWindowPosY = callbackLinker.upcallStub(mh_onGetWindowPosY, callbackDescriptor_onGetWindowPosY, upcallArena);
            java.lang.invoke.MethodHandle mh_onSetWindowSize = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onSetWindowSize", callbackMethodType_onSetWindowSize).bindTo(this);
            upcallStub_onSetWindowSize = callbackLinker.upcallStub(mh_onSetWindowSize, callbackDescriptor_onSetWindowSize, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowSizeX = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowSizeX", callbackMethodType_onGetWindowSizeX).bindTo(this);
            upcallStub_onGetWindowSizeX = callbackLinker.upcallStub(mh_onGetWindowSizeX, callbackDescriptor_onGetWindowSizeX, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowSizeY = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowSizeY", callbackMethodType_onGetWindowSizeY).bindTo(this);
            upcallStub_onGetWindowSizeY = callbackLinker.upcallStub(mh_onGetWindowSizeY, callbackDescriptor_onGetWindowSizeY, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowFramebufferScaleX = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowFramebufferScaleX", callbackMethodType_onGetWindowFramebufferScaleX).bindTo(this);
            upcallStub_onGetWindowFramebufferScaleX = callbackLinker.upcallStub(mh_onGetWindowFramebufferScaleX, callbackDescriptor_onGetWindowFramebufferScaleX, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowFramebufferScaleY = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowFramebufferScaleY", callbackMethodType_onGetWindowFramebufferScaleY).bindTo(this);
            upcallStub_onGetWindowFramebufferScaleY = callbackLinker.upcallStub(mh_onGetWindowFramebufferScaleY, callbackDescriptor_onGetWindowFramebufferScaleY, upcallArena);
            java.lang.invoke.MethodHandle mh_onSetWindowFocus = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onSetWindowFocus", callbackMethodType_onSetWindowFocus).bindTo(this);
            upcallStub_onSetWindowFocus = callbackLinker.upcallStub(mh_onSetWindowFocus, callbackDescriptor_onSetWindowFocus, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowFocus = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowFocus", callbackMethodType_onGetWindowFocus).bindTo(this);
            upcallStub_onGetWindowFocus = callbackLinker.upcallStub(mh_onGetWindowFocus, callbackDescriptor_onGetWindowFocus, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowMinimized = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowMinimized", callbackMethodType_onGetWindowMinimized).bindTo(this);
            upcallStub_onGetWindowMinimized = callbackLinker.upcallStub(mh_onGetWindowMinimized, callbackDescriptor_onGetWindowMinimized, upcallArena);
            java.lang.invoke.MethodHandle mh_onSetWindowTitle = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onSetWindowTitle", callbackMethodType_onSetWindowTitle).bindTo(this);
            upcallStub_onSetWindowTitle = callbackLinker.upcallStub(mh_onSetWindowTitle, callbackDescriptor_onSetWindowTitle, upcallArena);
            java.lang.invoke.MethodHandle mh_onSetWindowAlpha = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onSetWindowAlpha", callbackMethodType_onSetWindowAlpha).bindTo(this);
            upcallStub_onSetWindowAlpha = callbackLinker.upcallStub(mh_onSetWindowAlpha, callbackDescriptor_onSetWindowAlpha, upcallArena);
            java.lang.invoke.MethodHandle mh_onUpdateWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onUpdateWindow", callbackMethodType_onUpdateWindow).bindTo(this);
            upcallStub_onUpdateWindow = callbackLinker.upcallStub(mh_onUpdateWindow, callbackDescriptor_onUpdateWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onRenderWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onRenderWindow", callbackMethodType_onRenderWindow).bindTo(this);
            upcallStub_onRenderWindow = callbackLinker.upcallStub(mh_onRenderWindow, callbackDescriptor_onRenderWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onSwapBuffers = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onSwapBuffers", callbackMethodType_onSwapBuffers).bindTo(this);
            upcallStub_onSwapBuffers = callbackLinker.upcallStub(mh_onSwapBuffers, callbackDescriptor_onSwapBuffers, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowDpiScale = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowDpiScale", callbackMethodType_onGetWindowDpiScale).bindTo(this);
            upcallStub_onGetWindowDpiScale = callbackLinker.upcallStub(mh_onGetWindowDpiScale, callbackDescriptor_onGetWindowDpiScale, upcallArena);
            java.lang.invoke.MethodHandle mh_onChangedViewport = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onChangedViewport", callbackMethodType_onChangedViewport).bindTo(this);
            upcallStub_onChangedViewport = callbackLinker.upcallStub(mh_onChangedViewport, callbackDescriptor_onChangedViewport, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowWorkAreaInsetX = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowWorkAreaInsetX", callbackMethodType_onGetWindowWorkAreaInsetX).bindTo(this);
            upcallStub_onGetWindowWorkAreaInsetX = callbackLinker.upcallStub(mh_onGetWindowWorkAreaInsetX, callbackDescriptor_onGetWindowWorkAreaInsetX, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowWorkAreaInsetY = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowWorkAreaInsetY", callbackMethodType_onGetWindowWorkAreaInsetY).bindTo(this);
            upcallStub_onGetWindowWorkAreaInsetY = callbackLinker.upcallStub(mh_onGetWindowWorkAreaInsetY, callbackDescriptor_onGetWindowWorkAreaInsetY, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowWorkAreaInsetZ = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowWorkAreaInsetZ", callbackMethodType_onGetWindowWorkAreaInsetZ).bindTo(this);
            upcallStub_onGetWindowWorkAreaInsetZ = callbackLinker.upcallStub(mh_onGetWindowWorkAreaInsetZ, callbackDescriptor_onGetWindowWorkAreaInsetZ, upcallArena);
            java.lang.invoke.MethodHandle mh_onGetWindowWorkAreaInsetW = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onGetWindowWorkAreaInsetW", callbackMethodType_onGetWindowWorkAreaInsetW).bindTo(this);
            upcallStub_onGetWindowWorkAreaInsetW = callbackLinker.upcallStub(mh_onGetWindowWorkAreaInsetW, callbackDescriptor_onGetWindowWorkAreaInsetW, upcallArena);
            java.lang.invoke.MethodHandle mh_onCreateVkSurface = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onCreateVkSurface", callbackMethodType_onCreateVkSurface).bindTo(this);
            upcallStub_onCreateVkSurface = callbackLinker.upcallStub(mh_onCreateVkSurface, callbackDescriptor_onCreateVkSurface, upcallArena);
            java.lang.invoke.MethodHandle mh_onRendererCreateWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onRendererCreateWindow", callbackMethodType_onRendererCreateWindow).bindTo(this);
            upcallStub_onRendererCreateWindow = callbackLinker.upcallStub(mh_onRendererCreateWindow, callbackDescriptor_onRendererCreateWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onRendererDestroyWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onRendererDestroyWindow", callbackMethodType_onRendererDestroyWindow).bindTo(this);
            upcallStub_onRendererDestroyWindow = callbackLinker.upcallStub(mh_onRendererDestroyWindow, callbackDescriptor_onRendererDestroyWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onRendererSetWindowSize = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onRendererSetWindowSize", callbackMethodType_onRendererSetWindowSize).bindTo(this);
            upcallStub_onRendererSetWindowSize = callbackLinker.upcallStub(mh_onRendererSetWindowSize, callbackDescriptor_onRendererSetWindowSize, upcallArena);
            java.lang.invoke.MethodHandle mh_onRendererRenderWindow = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onRendererRenderWindow", callbackMethodType_onRendererRenderWindow).bindTo(this);
            upcallStub_onRendererRenderWindow = callbackLinker.upcallStub(mh_onRendererRenderWindow, callbackDescriptor_onRendererRenderWindow, upcallArena);
            java.lang.invoke.MethodHandle mh_onRendererSwapBuffers = callbackLookup.findVirtual(ImGuiViewportPlatformCallbacks.class, "internal_onRendererSwapBuffers", callbackMethodType_onRendererSwapBuffers).bindTo(this);
            upcallStub_onRendererSwapBuffers = callbackLinker.upcallStub(mh_onRendererSwapBuffers, callbackDescriptor_onRendererSwapBuffers, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onCreateWindow.address(), upcallStub_onDestroyWindow.address(), upcallStub_onShowWindow.address(), upcallStub_onSetWindowPos.address(), upcallStub_onGetWindowPosX.address(), upcallStub_onGetWindowPosY.address(), upcallStub_onSetWindowSize.address(), upcallStub_onGetWindowSizeX.address(), upcallStub_onGetWindowSizeY.address(), upcallStub_onGetWindowFramebufferScaleX.address(), upcallStub_onGetWindowFramebufferScaleY.address(), upcallStub_onSetWindowFocus.address(), upcallStub_onGetWindowFocus.address(), upcallStub_onGetWindowMinimized.address(), upcallStub_onSetWindowTitle.address(), upcallStub_onSetWindowAlpha.address(), upcallStub_onUpdateWindow.address(), upcallStub_onRenderWindow.address(), upcallStub_onSwapBuffers.address(), upcallStub_onGetWindowDpiScale.address(), upcallStub_onChangedViewport.address(), upcallStub_onGetWindowWorkAreaInsetX.address(), upcallStub_onGetWindowWorkAreaInsetY.address(), upcallStub_onGetWindowWorkAreaInsetZ.address(), upcallStub_onGetWindowWorkAreaInsetW.address(), upcallStub_onCreateVkSurface.address(), upcallStub_onRendererCreateWindow.address(), upcallStub_onRendererDestroyWindow.address(), upcallStub_onRendererSetWindowSize.address(), upcallStub_onRendererRenderWindow.address(), upcallStub_onRendererSwapBuffers.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onCreateWindow(ImGuiViewport viewport) {
    }

    private void internal_onCreateWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_0 == null)
            ImGuiViewport_TEMP_STATIC_GEN_0 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_0.internal_reset(viewport_addr, false);
        onCreateWindow(ImGuiViewport_TEMP_STATIC_GEN_0);
    }

    protected void onDestroyWindow(ImGuiViewport viewport) {
    }

    private void internal_onDestroyWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_1 == null)
            ImGuiViewport_TEMP_STATIC_GEN_1 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_1.internal_reset(viewport_addr, false);
        onDestroyWindow(ImGuiViewport_TEMP_STATIC_GEN_1);
    }

    protected void onShowWindow(ImGuiViewport viewport) {
    }

    private void internal_onShowWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_2 == null)
            ImGuiViewport_TEMP_STATIC_GEN_2 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_2.internal_reset(viewport_addr, false);
        onShowWindow(ImGuiViewport_TEMP_STATIC_GEN_2);
    }

    protected void onSetWindowPos(ImGuiViewport viewport, float x, float y) {
    }

    private void internal_onSetWindowPos(long viewport_addr, float x, float y) {
        if (ImGuiViewport_TEMP_STATIC_GEN_3 == null)
            ImGuiViewport_TEMP_STATIC_GEN_3 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_3.internal_reset(viewport_addr, false);
        onSetWindowPos(ImGuiViewport_TEMP_STATIC_GEN_3, x, y);
    }

    protected float onGetWindowPosX(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowPosX(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_4 == null)
            ImGuiViewport_TEMP_STATIC_GEN_4 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_4.internal_reset(viewport_addr, false);
        return onGetWindowPosX(ImGuiViewport_TEMP_STATIC_GEN_4);
    }

    protected float onGetWindowPosY(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowPosY(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_5 == null)
            ImGuiViewport_TEMP_STATIC_GEN_5 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_5.internal_reset(viewport_addr, false);
        return onGetWindowPosY(ImGuiViewport_TEMP_STATIC_GEN_5);
    }

    protected void onSetWindowSize(ImGuiViewport viewport, float width, float height) {
    }

    private void internal_onSetWindowSize(long viewport_addr, float width, float height) {
        if (ImGuiViewport_TEMP_STATIC_GEN_6 == null)
            ImGuiViewport_TEMP_STATIC_GEN_6 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_6.internal_reset(viewport_addr, false);
        onSetWindowSize(ImGuiViewport_TEMP_STATIC_GEN_6, width, height);
    }

    protected float onGetWindowSizeX(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowSizeX(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_7 == null)
            ImGuiViewport_TEMP_STATIC_GEN_7 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_7.internal_reset(viewport_addr, false);
        return onGetWindowSizeX(ImGuiViewport_TEMP_STATIC_GEN_7);
    }

    protected float onGetWindowSizeY(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowSizeY(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_8 == null)
            ImGuiViewport_TEMP_STATIC_GEN_8 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_8.internal_reset(viewport_addr, false);
        return onGetWindowSizeY(ImGuiViewport_TEMP_STATIC_GEN_8);
    }

    protected float onGetWindowFramebufferScaleX(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowFramebufferScaleX(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_9 == null)
            ImGuiViewport_TEMP_STATIC_GEN_9 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_9.internal_reset(viewport_addr, false);
        return onGetWindowFramebufferScaleX(ImGuiViewport_TEMP_STATIC_GEN_9);
    }

    protected float onGetWindowFramebufferScaleY(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowFramebufferScaleY(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_10 == null)
            ImGuiViewport_TEMP_STATIC_GEN_10 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_10.internal_reset(viewport_addr, false);
        return onGetWindowFramebufferScaleY(ImGuiViewport_TEMP_STATIC_GEN_10);
    }

    protected void onSetWindowFocus(ImGuiViewport viewport) {
    }

    private void internal_onSetWindowFocus(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_11 == null)
            ImGuiViewport_TEMP_STATIC_GEN_11 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_11.internal_reset(viewport_addr, false);
        onSetWindowFocus(ImGuiViewport_TEMP_STATIC_GEN_11);
    }

    protected boolean onGetWindowFocus(ImGuiViewport viewport) {
        return false;
    }

    private boolean internal_onGetWindowFocus(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_12 == null)
            ImGuiViewport_TEMP_STATIC_GEN_12 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_12.internal_reset(viewport_addr, false);
        return onGetWindowFocus(ImGuiViewport_TEMP_STATIC_GEN_12);
    }

    protected boolean onGetWindowMinimized(ImGuiViewport viewport) {
        return false;
    }

    private boolean internal_onGetWindowMinimized(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_13 == null)
            ImGuiViewport_TEMP_STATIC_GEN_13 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_13.internal_reset(viewport_addr, false);
        return onGetWindowMinimized(ImGuiViewport_TEMP_STATIC_GEN_13);
    }

    protected void onSetWindowTitle(ImGuiViewport viewport, NativeString title) {
    }

    private void internal_onSetWindowTitle(long viewport_addr, long title_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_14 == null)
            ImGuiViewport_TEMP_STATIC_GEN_14 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_14.internal_reset(viewport_addr, false);
        if (NativeString_TEMP_STATIC_GEN_0 == null)
            NativeString_TEMP_STATIC_GEN_0 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_0.internal_reset(title_addr, false);
        onSetWindowTitle(ImGuiViewport_TEMP_STATIC_GEN_14, NativeString_TEMP_STATIC_GEN_0);
    }

    protected void onSetWindowAlpha(ImGuiViewport viewport, float alpha) {
    }

    private void internal_onSetWindowAlpha(long viewport_addr, float alpha) {
        if (ImGuiViewport_TEMP_STATIC_GEN_15 == null)
            ImGuiViewport_TEMP_STATIC_GEN_15 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_15.internal_reset(viewport_addr, false);
        onSetWindowAlpha(ImGuiViewport_TEMP_STATIC_GEN_15, alpha);
    }

    protected void onUpdateWindow(ImGuiViewport viewport) {
    }

    private void internal_onUpdateWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_16 == null)
            ImGuiViewport_TEMP_STATIC_GEN_16 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_16.internal_reset(viewport_addr, false);
        onUpdateWindow(ImGuiViewport_TEMP_STATIC_GEN_16);
    }

    protected void onRenderWindow(ImGuiViewport viewport) {
    }

    private void internal_onRenderWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_17 == null)
            ImGuiViewport_TEMP_STATIC_GEN_17 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_17.internal_reset(viewport_addr, false);
        onRenderWindow(ImGuiViewport_TEMP_STATIC_GEN_17);
    }

    protected void onSwapBuffers(ImGuiViewport viewport) {
    }

    private void internal_onSwapBuffers(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_18 == null)
            ImGuiViewport_TEMP_STATIC_GEN_18 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_18.internal_reset(viewport_addr, false);
        onSwapBuffers(ImGuiViewport_TEMP_STATIC_GEN_18);
    }

    protected float onGetWindowDpiScale(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowDpiScale(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_19 == null)
            ImGuiViewport_TEMP_STATIC_GEN_19 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_19.internal_reset(viewport_addr, false);
        return onGetWindowDpiScale(ImGuiViewport_TEMP_STATIC_GEN_19);
    }

    protected void onChangedViewport(ImGuiViewport viewport) {
    }

    private void internal_onChangedViewport(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_20 == null)
            ImGuiViewport_TEMP_STATIC_GEN_20 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_20.internal_reset(viewport_addr, false);
        onChangedViewport(ImGuiViewport_TEMP_STATIC_GEN_20);
    }

    protected float onGetWindowWorkAreaInsetX(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowWorkAreaInsetX(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_21 == null)
            ImGuiViewport_TEMP_STATIC_GEN_21 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_21.internal_reset(viewport_addr, false);
        return onGetWindowWorkAreaInsetX(ImGuiViewport_TEMP_STATIC_GEN_21);
    }

    protected float onGetWindowWorkAreaInsetY(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowWorkAreaInsetY(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_22 == null)
            ImGuiViewport_TEMP_STATIC_GEN_22 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_22.internal_reset(viewport_addr, false);
        return onGetWindowWorkAreaInsetY(ImGuiViewport_TEMP_STATIC_GEN_22);
    }

    protected float onGetWindowWorkAreaInsetZ(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowWorkAreaInsetZ(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_23 == null)
            ImGuiViewport_TEMP_STATIC_GEN_23 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_23.internal_reset(viewport_addr, false);
        return onGetWindowWorkAreaInsetZ(ImGuiViewport_TEMP_STATIC_GEN_23);
    }

    protected float onGetWindowWorkAreaInsetW(ImGuiViewport viewport) {
        return 0;
    }

    private float internal_onGetWindowWorkAreaInsetW(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_24 == null)
            ImGuiViewport_TEMP_STATIC_GEN_24 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_24.internal_reset(viewport_addr, false);
        return onGetWindowWorkAreaInsetW(ImGuiViewport_TEMP_STATIC_GEN_24);
    }

    protected int onCreateVkSurface(ImGuiViewport viewport, long vk_instance, NativeObject vk_allocators, NativeObject out_vk_surface) {
        return 0;
    }

    private int internal_onCreateVkSurface(long viewport_addr, long vk_instance, long vk_allocators_addr, long out_vk_surface_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_25 == null)
            ImGuiViewport_TEMP_STATIC_GEN_25 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_25.internal_reset(viewport_addr, false);
        if (NativeObject_TEMP_STATIC_GEN_0 == null)
            NativeObject_TEMP_STATIC_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_0.internal_reset(vk_allocators_addr, false);
        if (NativeObject_TEMP_STATIC_GEN_1 == null)
            NativeObject_TEMP_STATIC_GEN_1 = NativeObject.native_new();
        NativeObject_TEMP_STATIC_GEN_1.internal_reset(out_vk_surface_addr, false);
        return onCreateVkSurface(ImGuiViewport_TEMP_STATIC_GEN_25, vk_instance, NativeObject_TEMP_STATIC_GEN_0, NativeObject_TEMP_STATIC_GEN_1);
    }

    protected void onRendererCreateWindow(ImGuiViewport viewport) {
    }

    private void internal_onRendererCreateWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_26 == null)
            ImGuiViewport_TEMP_STATIC_GEN_26 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_26.internal_reset(viewport_addr, false);
        onRendererCreateWindow(ImGuiViewport_TEMP_STATIC_GEN_26);
    }

    protected void onRendererDestroyWindow(ImGuiViewport viewport) {
    }

    private void internal_onRendererDestroyWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_27 == null)
            ImGuiViewport_TEMP_STATIC_GEN_27 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_27.internal_reset(viewport_addr, false);
        onRendererDestroyWindow(ImGuiViewport_TEMP_STATIC_GEN_27);
    }

    protected void onRendererSetWindowSize(ImGuiViewport viewport, float width, float height) {
    }

    private void internal_onRendererSetWindowSize(long viewport_addr, float width, float height) {
        if (ImGuiViewport_TEMP_STATIC_GEN_28 == null)
            ImGuiViewport_TEMP_STATIC_GEN_28 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_28.internal_reset(viewport_addr, false);
        onRendererSetWindowSize(ImGuiViewport_TEMP_STATIC_GEN_28, width, height);
    }

    protected void onRendererRenderWindow(ImGuiViewport viewport) {
    }

    private void internal_onRendererRenderWindow(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_29 == null)
            ImGuiViewport_TEMP_STATIC_GEN_29 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_29.internal_reset(viewport_addr, false);
        onRendererRenderWindow(ImGuiViewport_TEMP_STATIC_GEN_29);
    }

    protected void onRendererSwapBuffers(ImGuiViewport viewport) {
    }

    private void internal_onRendererSwapBuffers(long viewport_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_30 == null)
            ImGuiViewport_TEMP_STATIC_GEN_30 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_30.internal_reset(viewport_addr, false);
        onRendererSwapBuffers(ImGuiViewport_TEMP_STATIC_GEN_30);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onCreateWindow;

    private MemorySegment upcallStub_onDestroyWindow;

    private MemorySegment upcallStub_onShowWindow;

    private MemorySegment upcallStub_onSetWindowPos;

    private MemorySegment upcallStub_onGetWindowPosX;

    private MemorySegment upcallStub_onGetWindowPosY;

    private MemorySegment upcallStub_onSetWindowSize;

    private MemorySegment upcallStub_onGetWindowSizeX;

    private MemorySegment upcallStub_onGetWindowSizeY;

    private MemorySegment upcallStub_onGetWindowFramebufferScaleX;

    private MemorySegment upcallStub_onGetWindowFramebufferScaleY;

    private MemorySegment upcallStub_onSetWindowFocus;

    private MemorySegment upcallStub_onGetWindowFocus;

    private MemorySegment upcallStub_onGetWindowMinimized;

    private MemorySegment upcallStub_onSetWindowTitle;

    private MemorySegment upcallStub_onSetWindowAlpha;

    private MemorySegment upcallStub_onUpdateWindow;

    private MemorySegment upcallStub_onRenderWindow;

    private MemorySegment upcallStub_onSwapBuffers;

    private MemorySegment upcallStub_onGetWindowDpiScale;

    private MemorySegment upcallStub_onChangedViewport;

    private MemorySegment upcallStub_onGetWindowWorkAreaInsetX;

    private MemorySegment upcallStub_onGetWindowWorkAreaInsetY;

    private MemorySegment upcallStub_onGetWindowWorkAreaInsetZ;

    private MemorySegment upcallStub_onGetWindowWorkAreaInsetW;

    private MemorySegment upcallStub_onCreateVkSurface;

    private MemorySegment upcallStub_onRendererCreateWindow;

    private MemorySegment upcallStub_onRendererDestroyWindow;

    private MemorySegment upcallStub_onRendererSetWindowSize;

    private MemorySegment upcallStub_onRendererRenderWindow;

    private MemorySegment upcallStub_onRendererSwapBuffers;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onCreateWindow = null;
        upcallStub_onDestroyWindow = null;
        upcallStub_onShowWindow = null;
        upcallStub_onSetWindowPos = null;
        upcallStub_onGetWindowPosX = null;
        upcallStub_onGetWindowPosY = null;
        upcallStub_onSetWindowSize = null;
        upcallStub_onGetWindowSizeX = null;
        upcallStub_onGetWindowSizeY = null;
        upcallStub_onGetWindowFramebufferScaleX = null;
        upcallStub_onGetWindowFramebufferScaleY = null;
        upcallStub_onSetWindowFocus = null;
        upcallStub_onGetWindowFocus = null;
        upcallStub_onGetWindowMinimized = null;
        upcallStub_onSetWindowTitle = null;
        upcallStub_onSetWindowAlpha = null;
        upcallStub_onUpdateWindow = null;
        upcallStub_onRenderWindow = null;
        upcallStub_onSwapBuffers = null;
        upcallStub_onGetWindowDpiScale = null;
        upcallStub_onChangedViewport = null;
        upcallStub_onGetWindowWorkAreaInsetX = null;
        upcallStub_onGetWindowWorkAreaInsetY = null;
        upcallStub_onGetWindowWorkAreaInsetZ = null;
        upcallStub_onGetWindowWorkAreaInsetW = null;
        upcallStub_onCreateVkSurface = null;
        upcallStub_onRendererCreateWindow = null;
        upcallStub_onRendererDestroyWindow = null;
        upcallStub_onRendererSetWindowSize = null;
        upcallStub_onRendererRenderWindow = null;
        upcallStub_onRendererSwapBuffers = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onCreateWindow_fp, long onDestroyWindow_fp, long onShowWindow_fp, long onSetWindowPos_fp, long onGetWindowPosX_fp, long onGetWindowPosY_fp, long onSetWindowSize_fp, long onGetWindowSizeX_fp, long onGetWindowSizeY_fp, long onGetWindowFramebufferScaleX_fp, long onGetWindowFramebufferScaleY_fp, long onSetWindowFocus_fp, long onGetWindowFocus_fp, long onGetWindowMinimized_fp, long onSetWindowTitle_fp, long onSetWindowAlpha_fp, long onUpdateWindow_fp, long onRenderWindow_fp, long onSwapBuffers_fp, long onGetWindowDpiScale_fp, long onChangedViewport_fp, long onGetWindowWorkAreaInsetX_fp, long onGetWindowWorkAreaInsetY_fp, long onGetWindowWorkAreaInsetZ_fp, long onGetWindowWorkAreaInsetW_fp, long onCreateVkSurface_fp, long onRendererCreateWindow_fp, long onRendererDestroyWindow_fp, long onRendererSetWindowSize_fp, long onRendererRenderWindow_fp, long onRendererSwapBuffers_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ.invokeExact(this_addr, onCreateWindow_fp, onDestroyWindow_fp, onShowWindow_fp, onSetWindowPos_fp, onGetWindowPosX_fp, onGetWindowPosY_fp, onSetWindowSize_fp, onGetWindowSizeX_fp, onGetWindowSizeY_fp, onGetWindowFramebufferScaleX_fp, onGetWindowFramebufferScaleY_fp, onSetWindowFocus_fp, onGetWindowFocus_fp, onGetWindowMinimized_fp, onSetWindowTitle_fp, onSetWindowAlpha_fp, onUpdateWindow_fp, onRenderWindow_fp, onSwapBuffers_fp, onGetWindowDpiScale_fp, onChangedViewport_fp, onGetWindowWorkAreaInsetX_fp, onGetWindowWorkAreaInsetY_fp, onGetWindowWorkAreaInsetZ_fp, onGetWindowWorkAreaInsetW_fp, onCreateVkSurface_fp, onRendererCreateWindow_fp, onRendererDestroyWindow_fp, onRendererSetWindowSize_fp, onRendererRenderWindow_fp, onRendererSwapBuffers_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setCallbacks__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_setcallbacks", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_clearCallbacks__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_clearcallbacks", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setMainMonitor__JFFFFFFFFF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_setmainmonitor", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_setMainViewportPlatformHandle__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_setmainviewportplatformhandle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_clearViewportPlatformHandles__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_clearviewportplatformhandles", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguiviewportplatformcallbacks_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiviewportplatformcallbacks_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
