/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class ImGuiSelectionExternalStorage extends NativeObject {

    private NativeObject NativeObject_TEMP_GEN_0;

    static public final ImGuiSelectionExternalStorage NULL = ImGuiSelectionExternalStorage.native_new();

    public ImGuiSelectionExternalStorage() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiSelectionExternalStorage(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSelectionExternalStorage native_new() {
        return new ImGuiSelectionExternalStorage((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyRequests(ImGuiMultiSelectIO ms_io) {
        internal_native_ApplyRequests(native_address, ms_io.native_address);
    }

    public static void internal_native_ApplyRequests(long this_addr, long ms_io_addr) {
        try {
            FFMHandles.internal_native_ApplyRequests__JJ.invokeExact(this_addr, ms_io_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeObject get_UserData() {
        long addr = internal_native_get_UserData_addr(native_address);
        if (addr == 0)
            return NativeObject.NULL;
        if (NativeObject_TEMP_GEN_0 == null)
            NativeObject_TEMP_GEN_0 = NativeObject.native_new();
        NativeObject_TEMP_GEN_0.internal_reset(addr, false);
        return NativeObject_TEMP_GEN_0;
    }

    public static long internal_native_get_UserData_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_UserData_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_UserData(NativeObject UserData) {
        internal_native_set_UserData(native_address, UserData.native_void_address);
    }

    public static void internal_native_set_UserData(long this_addr, long UserData_addr) {
        try {
            FFMHandles.internal_native_set_UserData__JJ.invokeExact(this_addr, UserData_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguiselectionexternalstorage_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiselectionexternalstorage_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ApplyRequests__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiselectionexternalstorage_applyrequests", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_UserData_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguiselectionexternalstorage_get_userdata_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_UserData__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguiselectionexternalstorage_set_userdata", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
