/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class ImGuiListClipper extends NativeObject {

    static public final ImGuiListClipper NULL = ImGuiListClipper.native_new();

    public ImGuiListClipper() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiListClipper(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiListClipper native_new() {
        return new ImGuiListClipper((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Begin(int items_count, float items_height) {
        internal_native_Begin(native_address, items_count, items_height);
    }

    public static void internal_native_Begin(long this_addr, int items_count, float items_height) {
        try {
            FFMHandles.internal_native_Begin__JIF.invokeExact(this_addr, items_count, items_height);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Begin(int items_count) {
        internal_native_Begin(native_address, items_count);
    }

    public static void internal_native_Begin(long this_addr, int items_count) {
        try {
            FFMHandles.internal_native_Begin__JI.invokeExact(this_addr, items_count);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void End() {
        internal_native_End(native_address);
    }

    public static void internal_native_End(long this_addr) {
        try {
            FFMHandles.internal_native_End__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean Step() {
        return internal_native_Step(native_address);
    }

    public static boolean internal_native_Step(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_Step__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void IncludeItemByIndex(int item_index) {
        internal_native_IncludeItemByIndex(native_address, item_index);
    }

    public static void internal_native_IncludeItemByIndex(long this_addr, int item_index) {
        try {
            FFMHandles.internal_native_IncludeItemByIndex__JI.invokeExact(this_addr, item_index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void IncludeItemsByIndex(int item_begin, int item_end) {
        internal_native_IncludeItemsByIndex(native_address, item_begin, item_end);
    }

    public static void internal_native_IncludeItemsByIndex(long this_addr, int item_begin, int item_end) {
        try {
            FFMHandles.internal_native_IncludeItemsByIndex__JII.invokeExact(this_addr, item_begin, item_end);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SeekCursorForItem(int item_index) {
        internal_native_SeekCursorForItem(native_address, item_index);
    }

    public static void internal_native_SeekCursorForItem(long this_addr, int item_index) {
        try {
            FFMHandles.internal_native_SeekCursorForItem__JI.invokeExact(this_addr, item_index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_DisplayStart() {
        return internal_native_get_DisplayStart(native_address);
    }

    public static int internal_native_get_DisplayStart(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_DisplayStart__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_DisplayStart(int DisplayStart) {
        internal_native_set_DisplayStart(native_address, DisplayStart);
    }

    public static void internal_native_set_DisplayStart(long this_addr, int DisplayStart) {
        try {
            FFMHandles.internal_native_set_DisplayStart__JI.invokeExact(this_addr, DisplayStart);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_DisplayEnd() {
        return internal_native_get_DisplayEnd(native_address);
    }

    public static int internal_native_get_DisplayEnd(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_DisplayEnd__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_DisplayEnd(int DisplayEnd) {
        internal_native_set_DisplayEnd(native_address, DisplayEnd);
    }

    public static void internal_native_set_DisplayEnd(long this_addr, int DisplayEnd) {
        try {
            FFMHandles.internal_native_set_DisplayEnd__JI.invokeExact(this_addr, DisplayEnd);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_UserIndex() {
        return internal_native_get_UserIndex(native_address);
    }

    public static int internal_native_get_UserIndex(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_UserIndex__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_UserIndex(int UserIndex) {
        internal_native_set_UserIndex(native_address, UserIndex);
    }

    public static void internal_native_set_UserIndex(long this_addr, int UserIndex) {
        try {
            FFMHandles.internal_native_set_UserIndex__JI.invokeExact(this_addr, UserIndex);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Begin__JIF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_begin_l_i_f", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_Begin__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_begin_l_i", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_End__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_end", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Step__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_step", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IncludeItemByIndex__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_includeitembyindex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_IncludeItemsByIndex__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_includeitemsbyindex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SeekCursorForItem__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguilistclipper_seekcursorforitem", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_DisplayStart__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_get_displaystart", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_DisplayStart__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_set_displaystart", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_DisplayEnd__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_get_displayend", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_DisplayEnd__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_set_displayend", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_UserIndex__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_get_userindex", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_UserIndex__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguilistclipper_set_userindex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
