/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiSizeCallbackFunction extends NativeObject {

    static private ImGuiSizeCallbackData ImGuiSizeCallbackData_TEMP_STATIC_GEN_0;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onSizeConstraint = java.lang.invoke.MethodType.methodType(void.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSizeConstraint = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final ImGuiSizeCallbackFunction NULL = ImGuiSizeCallbackFunction.native_new();

    @Deprecated()
    protected ImGuiSizeCallbackFunction(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSizeCallbackFunction native_new() {
        return new ImGuiSizeCallbackFunction((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImGuiSizeCallbackFunction() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onSizeConstraint = callbackLookup.findVirtual(ImGuiSizeCallbackFunction.class, "internal_onSizeConstraint", callbackMethodType_onSizeConstraint).bindTo(this);
            upcallStub_onSizeConstraint = callbackLinker.upcallStub(mh_onSizeConstraint, callbackDescriptor_onSizeConstraint, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onSizeConstraint.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onSizeConstraint(ImGuiSizeCallbackData data) {
    }

    private void internal_onSizeConstraint(long data_addr) {
        if (ImGuiSizeCallbackData_TEMP_STATIC_GEN_0 == null)
            ImGuiSizeCallbackData_TEMP_STATIC_GEN_0 = ImGuiSizeCallbackData.native_new();
        ImGuiSizeCallbackData_TEMP_STATIC_GEN_0.internal_reset(data_addr, false);
        onSizeConstraint(ImGuiSizeCallbackData_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onSizeConstraint;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onSizeConstraint = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onSizeConstraint_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, onSizeConstraint_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguisizecallbackfunction_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguisizecallbackfunction_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguisizecallbackfunction_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
