/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ImGuiPlatformImeCallback extends NativeObject {

    static private ImGuiViewport ImGuiViewport_TEMP_STATIC_GEN_0;

    static private ImGuiPlatformImeData ImGuiPlatformImeData_TEMP_STATIC_GEN_0;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_onSetImeData = java.lang.invoke.MethodType.methodType(void.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_onSetImeData = java.lang.foreign.FunctionDescriptor.ofVoid(java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final ImGuiPlatformImeCallback NULL = ImGuiPlatformImeCallback.native_new();

    @Deprecated()
    protected ImGuiPlatformImeCallback(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiPlatformImeCallback native_new() {
        return new ImGuiPlatformImeCallback((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void Install(ImGuiPlatformIO platform_io, ImGuiPlatformImeCallback callback) {
        internal_native_Install(platform_io.native_address, callback.native_address);
    }

    public static void internal_native_Install(long platform_io_addr, long callback_addr) {
        try {
            FFMHandles.internal_native_Install__JJ.invokeExact(platform_io_addr, callback_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void Clear(ImGuiPlatformIO platform_io) {
        internal_native_Clear(platform_io.native_address);
    }

    public static void internal_native_Clear(long platform_io_addr) {
        try {
            FFMHandles.internal_native_Clear__J.invokeExact(platform_io_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImGuiPlatformImeCallback() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_onSetImeData = callbackLookup.findVirtual(ImGuiPlatformImeCallback.class, "internal_onSetImeData", callbackMethodType_onSetImeData).bindTo(this);
            upcallStub_onSetImeData = callbackLinker.upcallStub(mh_onSetImeData, callbackDescriptor_onSetImeData, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_onSetImeData.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected void onSetImeData(ImGuiViewport viewport, ImGuiPlatformImeData data) {
    }

    private void internal_onSetImeData(long viewport_addr, long data_addr) {
        if (ImGuiViewport_TEMP_STATIC_GEN_0 == null)
            ImGuiViewport_TEMP_STATIC_GEN_0 = ImGuiViewport.native_new();
        ImGuiViewport_TEMP_STATIC_GEN_0.internal_reset(viewport_addr, false);
        if (ImGuiPlatformImeData_TEMP_STATIC_GEN_0 == null)
            ImGuiPlatformImeData_TEMP_STATIC_GEN_0 = ImGuiPlatformImeData.native_new();
        ImGuiPlatformImeData_TEMP_STATIC_GEN_0.internal_reset(data_addr, false);
        onSetImeData(ImGuiViewport_TEMP_STATIC_GEN_0, ImGuiPlatformImeData_TEMP_STATIC_GEN_0);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_onSetImeData;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_onSetImeData = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long onSetImeData_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, onSetImeData_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiplatformimecallback_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Install__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiplatformimecallback_install", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Clear__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiplatformimecallback_clear", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguiplatformimecallback_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguiplatformimecallback_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
