/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.enums.ImGuiSortDirection;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class ImGuiTableColumnSortSpecs extends NativeObject {

    static public final ImGuiTableColumnSortSpecs NULL = ImGuiTableColumnSortSpecs.native_new();

    public ImGuiTableColumnSortSpecs() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiTableColumnSortSpecs(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiTableColumnSortSpecs native_new() {
        return new ImGuiTableColumnSortSpecs((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_ColumnUserID() {
        return internal_native_get_ColumnUserID(native_address);
    }

    public static int internal_native_get_ColumnUserID(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_ColumnUserID__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_ColumnIndex() {
        return internal_native_get_ColumnIndex(native_address);
    }

    public static short internal_native_get_ColumnIndex(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_ColumnIndex__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public short get_SortOrder() {
        return internal_native_get_SortOrder(native_address);
    }

    public static short internal_native_get_SortOrder(long this_addr) {
        try {
            return (short) FFMHandles.internal_native_get_SortOrder__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ImGuiSortDirection get_SortDirection() {
        int value = internal_native_get_SortDirection(native_address);
        ImGuiSortDirection[] values = ImGuiSortDirection.values();
        for (int i = 0; i < values.length; i++) {
            ImGuiSortDirection enumVal = values[i];
            if (enumVal != ImGuiSortDirection.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ImGuiSortDirection.CUSTOM.setValue(value);
    }

    public static int internal_native_get_SortDirection(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_SortDirection__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguitablecolumnsortspecs_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_imguitablecolumnsortspecs_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_ColumnUserID__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguitablecolumnsortspecs_get_columnuserid", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_ColumnIndex__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguitablecolumnsortspecs_get_columnindex", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_SortOrder__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguitablecolumnsortspecs_get_sortorder", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_SortDirection__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguitablecolumnsortspecs_get_sortdirection", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    }
}
