/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class ImGuiTableSortSpecsHelpers extends NativeObject {

    static private ImGuiTableColumnSortSpecs ImGuiTableColumnSortSpecs_TEMP_STATIC_GEN_0;

    static public final ImGuiTableSortSpecsHelpers NULL = ImGuiTableSortSpecsHelpers.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiTableSortSpecsHelpers(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiTableSortSpecsHelpers native_new() {
        return new ImGuiTableSortSpecsHelpers((byte) 0, (char) 0);
    }

    public static ImGuiTableColumnSortSpecs GetSpec(ImGuiTableSortSpecs sort_specs, int index) {
        long addr = internal_native_GetSpec_addr(sort_specs.native_address, index);
        if (addr == 0)
            return ImGuiTableColumnSortSpecs.NULL;
        if (ImGuiTableColumnSortSpecs_TEMP_STATIC_GEN_0 == null)
            ImGuiTableColumnSortSpecs_TEMP_STATIC_GEN_0 = ImGuiTableColumnSortSpecs.native_new();
        ImGuiTableColumnSortSpecs_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return ImGuiTableColumnSortSpecs_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_GetSpec_addr(long sort_specs_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetSpec_addr__JI.invokeExact(sort_specs_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_GetSpec_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_imguitablesortspecshelpers_getspec_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
