/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiTableColumnSortSpecs {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_get_ColumnUserID(long this_addr);

    public static native short internal_native_get_ColumnIndex(long this_addr);

    public static native short internal_native_get_SortOrder(long this_addr);

    public static native int internal_native_get_SortDirection(long this_addr);
}
