/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImFontAtlasRect {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native short internal_native_get_x(long this_addr);

    public static native short internal_native_get_y(long this_addr);

    public static native short internal_native_get_w(long this_addr);

    public static native short internal_native_get_h(long this_addr);

    public static native long internal_native_get_uv0_addr(long this_addr);

    public static native long internal_native_get_uv1_addr(long this_addr);
}
