/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiPlatformImeData {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native boolean internal_native_get_WantVisible(long this_addr);

    public static native void internal_native_set_WantVisible(long this_addr, boolean WantVisible);

    public static native boolean internal_native_get_WantTextInput(long this_addr);

    public static native void internal_native_set_WantTextInput(long this_addr, boolean WantTextInput);

    public static native long internal_native_get_InputPos_addr(long this_addr);

    public static native void internal_native_set_InputPos(long this_addr, long InputPos_addr);

    public static native float internal_native_get_InputLineHeight(long this_addr);

    public static native void internal_native_set_InputLineHeight(long this_addr, float InputLineHeight);

    public static native int internal_native_get_ViewportId(long this_addr);

    public static native void internal_native_set_ViewportId(long this_addr, int ViewportId);
}
