/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiStringList {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_Size(long this_addr);

    public static native boolean internal_native_Empty(long this_addr);

    public static native void internal_native_Clear(long this_addr);

    public static native void internal_native_Add(long this_addr, String value);

    public static native void internal_native_Set(long this_addr, int index, String value);

    public static native long internal_native_Get_addr(long this_addr, int index);
}
