/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiPlatformOpenInShellCallback {

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_Install(long platform_io_addr, long callback_addr);

    public static native void internal_native_Clear(long platform_io_addr);

    public static native long internal_native_create_addr();
}
