/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiSelectionExternalStorage {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_ApplyRequests(long this_addr, long ms_io_addr);

    public static native long internal_native_get_UserData_addr(long this_addr);

    public static native void internal_native_set_UserData(long this_addr, long UserData_addr);
}
