/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiListClipper {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_Begin(long this_addr, int items_count, float items_height);

    public static native void internal_native_Begin(long this_addr, int items_count);

    public static native void internal_native_End(long this_addr);

    public static native boolean internal_native_Step(long this_addr);

    public static native void internal_native_IncludeItemByIndex(long this_addr, int item_index);

    public static native void internal_native_IncludeItemsByIndex(long this_addr, int item_begin, int item_end);

    public static native void internal_native_SeekCursorForItem(long this_addr, int item_index);

    public static native int internal_native_get_DisplayStart(long this_addr);

    public static native void internal_native_set_DisplayStart(long this_addr, int DisplayStart);

    public static native int internal_native_get_DisplayEnd(long this_addr);

    public static native void internal_native_set_DisplayEnd(long this_addr, int DisplayEnd);

    public static native int internal_native_get_UserIndex(long this_addr);

    public static native void internal_native_set_UserIndex(long this_addr, int UserIndex);
}
