/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImDrawListSplitter {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_Clear(long this_addr);

    public static native void internal_native_ClearFreeMemory(long this_addr);

    public static native void internal_native_Split(long this_addr, long draw_list_addr, int count);

    public static native void internal_native_Merge(long this_addr, long draw_list_addr);

    public static native void internal_native_SetCurrentChannel(long this_addr, long draw_list_addr, int channel_idx);
}
