/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.natives;

import imgui.*;

final public class JNI_ImGuiTextFilter {

    public static native long internal_native_create_String_addr(String default_filter);

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native boolean internal_native_Draw(long this_addr, String label, float width);

    public static native boolean internal_native_Draw(long this_addr, String label);

    public static native boolean internal_native_Draw(long this_addr);

    public static native boolean internal_native_PassFilter(long this_addr, String text);

    public static native void internal_native_Build(long this_addr);

    public static native void internal_native_Clear(long this_addr);

    public static native boolean internal_native_IsActive(long this_addr);
}
