/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class TextEditorLineBreakConfig extends NativeObject {

    private NativeString NativeString_TEMP_GEN_0;

    private NativeString NativeString_TEMP_GEN_1;

    static public final TextEditorLineBreakConfig NULL = TextEditorLineBreakConfig.native_new();

    public TextEditorLineBreakConfig() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TextEditorLineBreakConfig(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static TextEditorLineBreakConfig native_new() {
        return new TextEditorLineBreakConfig((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUseUnicodeAnnex14(boolean value) {
        internal_native_SetUseUnicodeAnnex14(native_address, value);
    }

    public static void internal_native_SetUseUnicodeAnnex14(long this_addr, boolean value) {
        try {
            FFMHandles.internal_native_SetUseUnicodeAnnex14__JZ.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsUsingUnicodeAnnex14() {
        return internal_native_IsUsingUnicodeAnnex14(native_address);
    }

    public static boolean internal_native_IsUsingUnicodeAnnex14(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsUsingUnicodeAnnex14__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBreakAfter(String value) {
        internal_native_SetBreakAfter(native_address, value);
    }

    public static void internal_native_SetBreakAfter(long this_addr, String value) {
        try {
            FFMHandles.internal_native_SetBreakAfter__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(value));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString GetBreakAfter() {
        long addr = internal_native_GetBreakAfter_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_0 == null)
            NativeString_TEMP_GEN_0 = NativeString.native_new();
        NativeString_TEMP_GEN_0.internal_reset(addr, false);
        return NativeString_TEMP_GEN_0;
    }

    public static long internal_native_GetBreakAfter_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBreakAfter_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBreakBefore(String value) {
        internal_native_SetBreakBefore(native_address, value);
    }

    public static void internal_native_SetBreakBefore(long this_addr, String value) {
        try {
            FFMHandles.internal_native_SetBreakBefore__JLjava_lang_String_2.invokeExact(this_addr, com.github.xpenatan.jparser.runtime.helper.NativeUtils.toCString(value));
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public NativeString GetBreakBefore() {
        long addr = internal_native_GetBreakBefore_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_1 == null)
            NativeString_TEMP_GEN_1 = NativeString.native_new();
        NativeString_TEMP_GEN_1.internal_reset(addr, false);
        return NativeString_TEMP_GEN_1;
    }

    public static long internal_native_GetBreakBefore_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBreakBefore_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetRuleEnabled(TextEditorLineBreakRule rule, boolean value) {
        internal_native_SetRuleEnabled(native_address, rule.getValue(), value);
    }

    public static void internal_native_SetRuleEnabled(long this_addr, int rule, boolean value) {
        try {
            FFMHandles.internal_native_SetRuleEnabled__JIZ.invokeExact(this_addr, rule, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsRuleEnabled(TextEditorLineBreakRule rule) {
        return internal_native_IsRuleEnabled(native_address, rule.getValue());
    }

    public static boolean internal_native_IsRuleEnabled(long this_addr, int rule) {
        try {
            return (boolean) FFMHandles.internal_native_IsRuleEnabled__JI.invokeExact(this_addr, rule);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_extension_textedit_texteditorlinebreakconfig_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUseUnicodeAnnex14__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_setuseunicodeannex14", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_IsUsingUnicodeAnnex14__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_isusingunicodeannex14", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBreakAfter__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_setbreakafter", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_GetBreakAfter_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_extension_textedit_texteditorlinebreakconfig_getbreakafter_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBreakBefore__JLjava_lang_String_2 = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_setbreakbefore", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_GetBreakBefore_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("imgui_extension_textedit_texteditorlinebreakconfig_getbreakbefore_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetRuleEnabled__JIZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_setruleenabled", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_IsRuleEnabled__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("imgui_extension_textedit_texteditorlinebreakconfig_isruleenabled", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
