/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.enums.natives;

import imgui.enums.*;

final public class JNI_ImGuiItemFlags {

    static native public int ImGuiItemFlags_None_NATIVE();

    static native public int ImGuiItemFlags_NoTabStop_NATIVE();

    static native public int ImGuiItemFlags_NoNav_NATIVE();

    static native public int ImGuiItemFlags_NoNavDefaultFocus_NATIVE();

    static native public int ImGuiItemFlags_ButtonRepeat_NATIVE();

    static native public int ImGuiItemFlags_AutoClosePopups_NATIVE();

    static native public int ImGuiItemFlags_AllowDuplicateId_NATIVE();

    static native public int ImGuiItemFlags_LiveEditOnInputText_NATIVE();

    static native public int ImGuiItemFlags_LiveEditOnInputScalar_NATIVE();

    static native public int ImGuiItemFlags_LiveEditOnInput_NATIVE();

    static native public int ImGuiItemFlags_Disabled_NATIVE();
}
