/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.ImVec2;

public final class TextDiff extends NativeObject {

    static public final TextDiff NULL = TextDiff.native_new();

    public TextDiff() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TextDiff(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static TextDiff native_new() {
        return new TextDiff((byte) 0, (char) 0);
    }

    public void SetSideBySideMode(boolean value) {
    }

    public boolean GetSideBySideMode() {
        return false;
    }

    public void SetTabSize(long value) {
    }

    public long GetTabSize() {
        return 0;
    }

    public void SetLineSpacing(float value) {
    }

    public float GetLineSpacing() {
        return 0;
    }

    public void SetWordWrapEnabled(boolean value) {
    }

    public boolean IsWordWrapEnabled() {
        return false;
    }

    public void SetShowWhitespacesEnabled(boolean value) {
    }

    public boolean IsShowWhitespacesEnabled() {
        return false;
    }

    public void SetShowSpacesEnabled(boolean value) {
    }

    public boolean IsShowSpacesEnabled() {
        return false;
    }

    public void SetShowTabsEnabled(boolean value) {
    }

    public boolean IsShowTabsEnabled() {
        return false;
    }

    public void SetShowScrollbarMiniMapEnabled(boolean value) {
    }

    public boolean IsShowScrollbarMiniMapEnabled() {
        return false;
    }

    public void SetLanguage(TextEditorLanguage language) {
    }

    public TextEditorLanguage GetLanguage() {
        return null;
    }

    public void SetColors(int addedColor, int deletedColor) {
    }

    public void SetPalette(TextEditorPalette palette) {
    }

    public void SetPaletteColor(TextEditorColor color, int value) {
    }

    public int GetPaletteColor(TextEditorColor color) {
        return 0;
    }

    public void SetFocus() {
    }

    public void SetText(String left, String right) {
    }

    public void Render(String title, ImVec2 size, int childFlags, int windowFlags) {
    }

    public void Render(String title, ImVec2 size, int childFlags) {
    }

    public void Render(String title, ImVec2 size) {
    }

    public void Render(String title) {
    }
}
