/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum TextEditorColor implements NativeEnum<TextEditorColor> {

    CUSTOM(0),
    Text(Text_NATIVE()),
    Keyword(Keyword_NATIVE()),
    Declaration(Declaration_NATIVE()),
    Number(Number_NATIVE()),
    String(String_NATIVE()),
    Punctuation(Punctuation_NATIVE()),
    Preprocessor(Preprocessor_NATIVE()),
    Identifier(Identifier_NATIVE()),
    KnownIdentifier(KnownIdentifier_NATIVE()),
    Comment(Comment_NATIVE()),
    Background(Background_NATIVE()),
    Cursor(Cursor_NATIVE()),
    Selection(Selection_NATIVE()),
    Whitespace(Whitespace_NATIVE()),
    MatchingBracketBackground(MatchingBracketBackground_NATIVE()),
    MatchingBracketActive(MatchingBracketActive_NATIVE()),
    MatchingBracketLevel1(MatchingBracketLevel1_NATIVE()),
    MatchingBracketLevel2(MatchingBracketLevel2_NATIVE()),
    MatchingBracketLevel3(MatchingBracketLevel3_NATIVE()),
    MatchingBracketError(MatchingBracketError_NATIVE()),
    LineNumber(LineNumber_NATIVE()),
    CurrentLineNumber(CurrentLineNumber_NATIVE());

    private int value;

    private TextEditorColor(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public TextEditorColor setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public TextEditorColor getCustom() {
        return CUSTOM;
    }

    private static native int Text_NATIVE();

    private static native int Keyword_NATIVE();

    private static native int Declaration_NATIVE();

    private static native int Number_NATIVE();

    private static native int String_NATIVE();

    private static native int Punctuation_NATIVE();

    private static native int Preprocessor_NATIVE();

    private static native int Identifier_NATIVE();

    private static native int KnownIdentifier_NATIVE();

    private static native int Comment_NATIVE();

    private static native int Background_NATIVE();

    private static native int Cursor_NATIVE();

    private static native int Selection_NATIVE();

    private static native int Whitespace_NATIVE();

    private static native int MatchingBracketBackground_NATIVE();

    private static native int MatchingBracketActive_NATIVE();

    private static native int MatchingBracketLevel1_NATIVE();

    private static native int MatchingBracketLevel2_NATIVE();

    private static native int MatchingBracketLevel3_NATIVE();

    private static native int MatchingBracketError_NATIVE();

    private static native int LineNumber_NATIVE();

    private static native int CurrentLineNumber_NATIVE();
}
