/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit.natives;

import imgui.extension.textedit.*;

final public class JNI_TextDiff {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetSideBySideMode(long this_addr, boolean value);

    public static native boolean internal_native_GetSideBySideMode(long this_addr);

    public static native void internal_native_SetTabSize(long this_addr, long value);

    public static native long internal_native_GetTabSize(long this_addr);

    public static native void internal_native_SetLineSpacing(long this_addr, float value);

    public static native float internal_native_GetLineSpacing(long this_addr);

    public static native void internal_native_SetWordWrapEnabled(long this_addr, boolean value);

    public static native boolean internal_native_IsWordWrapEnabled(long this_addr);

    public static native void internal_native_SetShowWhitespacesEnabled(long this_addr, boolean value);

    public static native boolean internal_native_IsShowWhitespacesEnabled(long this_addr);

    public static native void internal_native_SetShowSpacesEnabled(long this_addr, boolean value);

    public static native boolean internal_native_IsShowSpacesEnabled(long this_addr);

    public static native void internal_native_SetShowTabsEnabled(long this_addr, boolean value);

    public static native boolean internal_native_IsShowTabsEnabled(long this_addr);

    public static native void internal_native_SetShowScrollbarMiniMapEnabled(long this_addr, boolean value);

    public static native boolean internal_native_IsShowScrollbarMiniMapEnabled(long this_addr);

    public static native void internal_native_SetLanguage(long this_addr, int language);

    public static native int internal_native_GetLanguage(long this_addr);

    public static native void internal_native_SetColors(long this_addr, int addedColor, int deletedColor);

    public static native void internal_native_SetPalette(long this_addr, int palette);

    public static native void internal_native_SetPaletteColor(long this_addr, int color, int value);

    public static native int internal_native_GetPaletteColor(long this_addr, int color);

    public static native void internal_native_SetFocus(long this_addr);

    public static native void internal_native_SetText(long this_addr, String left, String right);

    public static native void internal_native_Render(long this_addr, String title, long size_addr, int childFlags, int windowFlags);

    public static native void internal_native_Render(long this_addr, String title, long size_addr, int childFlags);

    public static native void internal_native_Render(long this_addr, String title, long size_addr);

    public static native void internal_native_Render(long this_addr, String title);
}
