/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui.extension.textedit.natives;

import imgui.extension.textedit.*;

final public class JNI_TextEditorScroll {

    static native public int AlignTop_NATIVE();

    static native public int AlignMiddle_NATIVE();

    static native public int AlignBottom_NATIVE();
}
