/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import imgui.enums.ImDrawFlags;
import imgui.enums.ImDrawListFlags;

public final class ImDrawList extends NativeObject {

    static public final ImDrawList NULL = ImDrawList.native_new();

    public ImDrawList(ImDrawListSharedData shared_data) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImDrawList(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImDrawList native_new() {
        return new ImDrawList((byte) 0, (char) 0);
    }

    public void PushClipRect(ImVec2 cr_min, ImVec2 cr_max, boolean intersect_with_current_clip_rect) {
    }

    public void PushClipRect(ImVec2 cr_min, ImVec2 cr_max) {
    }

    public void PushClipRectFullScreen() {
    }

    public void PopClipRect() {
    }

    public void PushTexture(ImTextureRef tex_ref) {
    }

    public void PopTexture() {
    }

    public ImVec2 GetClipRectMin() {
        return null;
    }

    public ImVec2 GetClipRectMax() {
        return null;
    }

    public void AddLine(ImVec2 p1, ImVec2 p2, int col, float thickness) {
    }

    public void AddLine(ImVec2 p1, ImVec2 p2, int col) {
    }

    public void AddLineH(float min_x, float max_x, float y, int col, float thickness) {
    }

    public void AddLineH(float min_x, float max_x, float y, int col) {
    }

    public void AddLineV(float x, float min_y, float max_y, int col, float thickness) {
    }

    public void AddLineV(float x, float min_y, float max_y, int col) {
    }

    public void AddRect(ImVec2 p_min, ImVec2 p_max, int col, float rounding, float thickness, ImDrawFlags flags) {
    }

    public void AddRect(ImVec2 p_min, ImVec2 p_max, int col, float rounding, float thickness) {
    }

    public void AddRect(ImVec2 p_min, ImVec2 p_max, int col, float rounding) {
    }

    public void AddRect(ImVec2 p_min, ImVec2 p_max, int col) {
    }

    public void AddRectFilled(ImVec2 p_min, ImVec2 p_max, int col, float rounding, ImDrawFlags flags) {
    }

    public void AddRectFilled(ImVec2 p_min, ImVec2 p_max, int col, float rounding) {
    }

    public void AddRectFilled(ImVec2 p_min, ImVec2 p_max, int col) {
    }

    public void AddRectFilledMultiColor(ImVec2 p_min, ImVec2 p_max, int col_upr_left, int col_upr_right, int col_bot_right, int col_bot_left) {
    }

    public void AddQuad(ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, int col, float thickness) {
    }

    public void AddQuad(ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, int col) {
    }

    public void AddQuadFilled(ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, int col) {
    }

    public void AddTriangle(ImVec2 p1, ImVec2 p2, ImVec2 p3, int col, float thickness) {
    }

    public void AddTriangle(ImVec2 p1, ImVec2 p2, ImVec2 p3, int col) {
    }

    public void AddTriangleFilled(ImVec2 p1, ImVec2 p2, ImVec2 p3, int col) {
    }

    public void AddCircle(ImVec2 center, float radius, int col, int num_segments, float thickness) {
    }

    public void AddCircle(ImVec2 center, float radius, int col, int num_segments) {
    }

    public void AddCircle(ImVec2 center, float radius, int col) {
    }

    public void AddCircleFilled(ImVec2 center, float radius, int col, int num_segments) {
    }

    public void AddCircleFilled(ImVec2 center, float radius, int col) {
    }

    public void AddNgon(ImVec2 center, float radius, int col, int num_segments, float thickness) {
    }

    public void AddNgon(ImVec2 center, float radius, int col, int num_segments) {
    }

    public void AddNgonFilled(ImVec2 center, float radius, int col, int num_segments) {
    }

    public void AddEllipse(ImVec2 center, ImVec2 radius, int col, float rot, int num_segments, float thickness) {
    }

    public void AddEllipse(ImVec2 center, ImVec2 radius, int col, float rot, int num_segments) {
    }

    public void AddEllipse(ImVec2 center, ImVec2 radius, int col, float rot) {
    }

    public void AddEllipse(ImVec2 center, ImVec2 radius, int col) {
    }

    public void AddEllipseFilled(ImVec2 center, ImVec2 radius, int col, float rot, int num_segments) {
    }

    public void AddEllipseFilled(ImVec2 center, ImVec2 radius, int col, float rot) {
    }

    public void AddEllipseFilled(ImVec2 center, ImVec2 radius, int col) {
    }

    public void AddText(ImVec2 pos, int col, String text_begin, String text_end) {
    }

    public void AddText(ImVec2 pos, int col, String text_begin) {
    }

    public void AddBezierCubic(ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, int col, float thickness, int num_segments) {
    }

    public void AddBezierCubic(ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, int col, float thickness) {
    }

    public void AddBezierQuadratic(ImVec2 p1, ImVec2 p2, ImVec2 p3, int col, float thickness, int num_segments) {
    }

    public void AddBezierQuadratic(ImVec2 p1, ImVec2 p2, ImVec2 p3, int col, float thickness) {
    }

    public void AddPolyline(ImVec2 points, int num_points, int col, float thickness, ImDrawFlags flags) {
    }

    public void AddPolyline(ImVec2 points, int num_points, int col, float thickness) {
    }

    public void AddConvexPolyFilled(ImVec2 points, int num_points, int col) {
    }

    public void AddConcavePolyFilled(ImVec2 points, int num_points, int col) {
    }

    public void AddImage(ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min, ImVec2 uv_max, int col) {
    }

    public void AddImage(ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min, ImVec2 uv_max) {
    }

    public void AddImage(ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min) {
    }

    public void AddImage(ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max) {
    }

    public void AddImageQuad(ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, ImVec2 uv1, ImVec2 uv2, ImVec2 uv3, ImVec2 uv4, int col) {
    }

    public void AddImageQuad(ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, ImVec2 uv1, ImVec2 uv2, ImVec2 uv3, ImVec2 uv4) {
    }

    public void AddImageQuad(ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, ImVec2 uv1, ImVec2 uv2, ImVec2 uv3) {
    }

    public void AddImageQuad(ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, ImVec2 uv1, ImVec2 uv2) {
    }

    public void AddImageQuad(ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, ImVec2 uv1) {
    }

    public void AddImageQuad(ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4) {
    }

    public void AddImageRounded(ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min, ImVec2 uv_max, int col, float rounding, ImDrawFlags flags) {
    }

    public void AddImageRounded(ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min, ImVec2 uv_max, int col, float rounding) {
    }

    public void PathClear() {
    }

    public void PathLineTo(ImVec2 pos) {
    }

    public void PathLineToMergeDuplicate(ImVec2 pos) {
    }

    public void PathArcTo(ImVec2 center, float radius, float a_min, float a_max, int num_segments) {
    }

    public void PathArcTo(ImVec2 center, float radius, float a_min, float a_max) {
    }

    public void PathArcToFast(ImVec2 center, float radius, int a_min_of_12, int a_max_of_12) {
    }

    public void PathEllipticalArcTo(ImVec2 center, ImVec2 radius, float rot, float a_min, float a_max, int num_segments) {
    }

    public void PathEllipticalArcTo(ImVec2 center, ImVec2 radius, float rot, float a_min, float a_max) {
    }

    public void PathBezierCubicCurveTo(ImVec2 p2, ImVec2 p3, ImVec2 p4, int num_segments) {
    }

    public void PathBezierCubicCurveTo(ImVec2 p2, ImVec2 p3, ImVec2 p4) {
    }

    public void PathBezierQuadraticCurveTo(ImVec2 p2, ImVec2 p3, int num_segments) {
    }

    public void PathBezierQuadraticCurveTo(ImVec2 p2, ImVec2 p3) {
    }

    public void PathRect(ImVec2 rect_min, ImVec2 rect_max, float rounding, ImDrawFlags flags) {
    }

    public void PathRect(ImVec2 rect_min, ImVec2 rect_max, float rounding) {
    }

    public void PathRect(ImVec2 rect_min, ImVec2 rect_max) {
    }

    public void PathFillConvex(int col) {
    }

    public void PathStroke(int col, float thickness, ImDrawFlags flags) {
    }

    public void PathStroke(int col, float thickness) {
    }

    public void PathStroke(int col) {
    }

    public void AddDrawCmd() {
    }

    public ImDrawList CloneOutput() {
        return null;
    }

    public void PrimReserve(int idx_count, int vtx_count) {
    }

    public void PrimUnreserve(int idx_count, int vtx_count) {
    }

    public void PrimRect(ImVec2 a, ImVec2 b, int col) {
    }

    public void PrimRectUV(ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b, int col) {
    }

    public void PrimQuadUV(ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b, ImVec2 uv_c, ImVec2 uv_d, int col) {
    }

    public void ChannelsSplit(int count) {
    }

    public void ChannelsMerge() {
    }

    public void ChannelsSetCurrent(int n) {
    }

    public ImVectorImDrawCmd get_CmdBuffer() {
        return null;
    }

    public void set_CmdBuffer(ImVectorImDrawCmd CmdBuffer) {
    }

    public ImVectorImDrawIdx get_IdxBuffer() {
        return null;
    }

    public void set_IdxBuffer(ImVectorImDrawIdx IdxBuffer) {
    }

    public ImVectorImDrawVert get_VtxBuffer() {
        return null;
    }

    public void set_VtxBuffer(ImVectorImDrawVert VtxBuffer) {
    }

    public ImDrawListFlags get_Flags() {
        return null;
    }

    public void set_Flags(ImDrawListFlags Flags) {
    }
}
