/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImFontGlyph extends NativeObject {

    static public final ImFontGlyph NULL = ImFontGlyph.native_new();

    public ImFontGlyph() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImFontGlyph(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImFontGlyph native_new() {
        return new ImFontGlyph((byte) 0, (char) 0);
    }

    public boolean get_Colored() {
        return false;
    }

    public boolean get_Visible() {
        return false;
    }

    public int get_SourceIdx() {
        return 0;
    }

    public int get_Codepoint() {
        return 0;
    }

    public float get_AdvanceX() {
        return 0;
    }

    public float get_X0() {
        return 0;
    }

    public float get_Y0() {
        return 0;
    }

    public float get_X1() {
        return 0;
    }

    public float get_Y1() {
        return 0;
    }

    public float get_U0() {
        return 0;
    }

    public float get_V0() {
        return 0;
    }

    public float get_U1() {
        return 0;
    }

    public float get_V1() {
        return 0;
    }
}
