/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImFontAtlasRect extends NativeObject {

    static public final ImFontAtlasRect NULL = ImFontAtlasRect.native_new();

    public ImFontAtlasRect() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImFontAtlasRect(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImFontAtlasRect native_new() {
        return new ImFontAtlasRect((byte) 0, (char) 0);
    }

    public short get_x() {
        return 0;
    }

    public short get_y() {
        return 0;
    }

    public short get_w() {
        return 0;
    }

    public short get_h() {
        return 0;
    }

    public ImVec2 get_uv0() {
        return null;
    }

    public ImVec2 get_uv1() {
        return null;
    }
}
