/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImGuiSelectionExternalStorageAdapter extends NativeObject {

    static public final ImGuiSelectionExternalStorageAdapter NULL = ImGuiSelectionExternalStorageAdapter.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiSelectionExternalStorageAdapter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSelectionExternalStorageAdapter native_new() {
        return new ImGuiSelectionExternalStorageAdapter((byte) 0, (char) 0);
    }

    public static void Install(ImGuiSelectionExternalStorage storage, ImGuiSelectionExternalStorageAdapter adapter) {
    }

    public static void Clear(ImGuiSelectionExternalStorage storage) {
    }

    public ImGuiSelectionExternalStorageAdapter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected void onSetItemSelected(int index, boolean selected) {
    }

    private void internal_onSetItemSelected(int index, boolean selected) {
        onSetItemSelected(index, selected);
    }

    public static native long internal_native_create_addr();
}
