/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiSelectionBasicStorage extends NativeObject {

    static public final ImGuiSelectionBasicStorage NULL = ImGuiSelectionBasicStorage.native_new();

    public ImGuiSelectionBasicStorage() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiSelectionBasicStorage(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiSelectionBasicStorage native_new() {
        return new ImGuiSelectionBasicStorage((byte) 0, (char) 0);
    }

    public void ApplyRequests(ImGuiMultiSelectIO ms_io) {
    }

    public boolean Contains(int id) {
        return false;
    }

    public void Clear() {
    }

    public void Swap(ImGuiSelectionBasicStorage other) {
    }

    public void SetItemSelected(int id, boolean selected) {
    }

    public int GetStorageIdFromIndex(int index) {
        return 0;
    }

    public int get_Size() {
        return 0;
    }

    public boolean get_PreserveOrder() {
        return false;
    }

    public void set_PreserveOrder(boolean PreserveOrder) {
    }

    public NativeObject get_UserData() {
        return null;
    }

    public void set_UserData(NativeObject UserData) {
    }
}
