/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiOnceUponAFrame extends NativeObject {

    static public final ImGuiOnceUponAFrame NULL = ImGuiOnceUponAFrame.native_new();

    public ImGuiOnceUponAFrame() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiOnceUponAFrame(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiOnceUponAFrame native_new() {
        return new ImGuiOnceUponAFrame((byte) 0, (char) 0);
    }

    public int get_RefFrame() {
        return 0;
    }

    public void set_RefFrame(int RefFrame) {
    }
}
