/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;

public class ImGuiItemGetter extends NativeObject {

    static private NativeString NativeString_TEMP_STATIC_GEN_0;

    static public final ImGuiItemGetter NULL = ImGuiItemGetter.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiItemGetter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiItemGetter native_new() {
        return new ImGuiItemGetter((byte) 0, (char) 0);
    }

    public ImGuiItemGetter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected void onGetItem(int index, NativeString value_out) {
    }

    private void internal_onGetItem(int index, long value_out_addr) {
        if (NativeString_TEMP_STATIC_GEN_0 == null)
            NativeString_TEMP_STATIC_GEN_0 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_0.internal_reset(value_out_addr, false);
        onGetItem(index, NativeString_TEMP_STATIC_GEN_0);
    }

    public static native long internal_native_create_addr();
}
