/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public class ImGuiPlotGetter extends NativeObject {

    static public final ImGuiPlotGetter NULL = ImGuiPlotGetter.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiPlotGetter(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiPlotGetter native_new() {
        return new ImGuiPlotGetter((byte) 0, (char) 0);
    }

    public ImGuiPlotGetter() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected float onGetValue(int index) {
        return 0;
    }

    private float internal_onGetValue(int index) {
        return onGetValue(index);
    }

    public static native long internal_native_create_addr();
}
