/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package imgui;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ImGuiPlatformImeData extends NativeObject {

    static public final ImGuiPlatformImeData NULL = ImGuiPlatformImeData.native_new();

    public ImGuiPlatformImeData() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ImGuiPlatformImeData(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ImGuiPlatformImeData native_new() {
        return new ImGuiPlatformImeData((byte) 0, (char) 0);
    }

    public boolean get_WantVisible() {
        return false;
    }

    public void set_WantVisible(boolean WantVisible) {
    }

    public boolean get_WantTextInput() {
        return false;
    }

    public void set_WantTextInput(boolean WantTextInput) {
    }

    public ImVec2 get_InputPos() {
        return null;
    }

    public void set_InputPos(ImVec2 InputPos) {
    }

    public float get_InputLineHeight() {
        return 0;
    }

    public void set_InputLineHeight(float InputLineHeight) {
    }

    public int get_ViewportId() {
        return 0;
    }

    public void set_ViewportId(int ViewportId) {
    }
}
