name: Build Release

on:
  push:
    branches:
      - "release"

jobs:
  build-and-upload:
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/build_and_upload.yml
    with:
      isRelease: true
      shouldUpload: true
    secrets: inherit
