name: Build Snapshot

on:
  push:
    branches:
      - "master"

jobs:
  build-and-upload:
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/build_and_upload.yml
    with:
      isRelease: false
      shouldUpload: true
    secrets: inherit
